### ISSUE TITLE
Support for connection throgh Proxy servers ... starting with "basic" authentication ... 

### ISSUE THREAD

**Issue by ramshankerji** [fritzy/SleekXMPP#1]
Please make support for proxy servers with basic authentication. These kind of net connectivity is more popular in school/university internal networks.

To achive this 
1.Connect method need to modified to connect to proxyserver:port 1st ... using the same connect method of socket obj.
2.Than send the connection request to xmpp server along with autherization header through the socket connected to proxy server.

PS: Follwing exmaple is taken form xmpppy .

connector = ['CONNECT %s:%s HTTP/1.0'%self._server,
                    'Proxy-Connection: Keep-Alive',
                    'Pragma: no-cache',
                    'Host: %s:%s'%self._server,
                    'User-Agent: HTTPPROXYsocket/v0.1']
                if self._proxy.has_key('user') and self._proxy.has_key('password'):
                    credentials = '%s:%s'%(self._proxy['user'],self._proxy['password'])
                    credentials = base64.encodestring(credentials).strip()
                    connector.append('Proxy-Authorization: Basic '+credentials)
                connector.append('\r\n')
so.send('\r\n'.join(connector))

**Comment by legastero** [comment]
Well, it took a while, but we finally got around to this one.

The develop branch now includes basic HTTP Proxy support.
