### ISSUE TITLE
Do not fire events for sometimes

### ISSUE THREAD

**Issue by minhnhb** [fritzy/SleekXMPP#100]
In our case, after a long-enough idle time, the server still receive messages but it does not fire any event.

I.e, the client send a disco info iq to server, in server we will see 2 log messages:

2011-09-10 08:31:48    7596      DEBUG     sleekxmpp.xmlstream.xmlstream    RECV: &lt;iq from="CLIENT" type="get" to="SERVER">&lt;query xmlns="http://jabber.org/protocol/disco#info" />&lt;/iq>
2011-09-10 08:31:48    7596      DEBUG     sleekxmpp.plugins.xep_0030.disco    Received disco info query from CLIENT to SERVER.

But we see that after few hours, the server only received the message but it did not fire the appropriate event.

I don't know what is the cause and how to work around.

**Comment by legastero** [comment]
I'm not 100% sure, but my first guess is that something is blocking the event queue. Non-threaded event handlers, scheduled events, and stanza handlers all run out of the same queue in the same thread. If you are using any blocking operations in those functions and they end up blocking indefinitely then event queue processing will block as well.

What event handlers are you using, and are you registering any stanza handlers (like for handling custom Iq payloads)?

**Comment by minhnhb** [comment]
Thanks Legastero, I've figured it out. As you said, it was blocked by a non-threaded job.
