### ISSUE TITLE
Can't add event handlers to xmlstream after removing one

### ISSUE THREAD

**Issue by teisenbe** [fritzy/SleekXMPP#103]
To reproduce:  Call XMLStream.add_event_handler, then XMLStream.del_event_handler, then XMLStream.add_event_handler on the same name and pointer.

Result: Exception due to self.__event_handlers[name] being a filter object, which does not have an append method.

**Comment by teisenbe** [comment]
The fix is pretty simple, patch follows (I'm unfamiliar with github, and didn't see a way to attach a patch, so it's inline)

diff --git a/sleekxmpp/xmlstream/xmlstream.py b/sleekxmpp/xmlstream/xmlstream.py
index 5ba4269..e1caf1e 100644
--- a/sleekxmpp/xmlstream/xmlstream.py
+++ b/sleekxmpp/xmlstream/xmlstream.py
@@ -673,8 +673,8 @@ class XMLStream(object):
         def filter_pointers(handler):
             return handler[0] != pointer
-        self.__event_handlers[name] = filter(filter_pointers,
-                                             self.__event_handlers[name])
-        self.__event_handlers[name] = list(filter(filter_pointers,
- ```
                                               self.__event_handlers[name]))
  ```
  
   def event_handled(self, name):
       """

**Comment by legastero** [comment]
Ah, the joy of Python 3's slightly different semantics. This is fixed in develop now.
