### ISSUE TITLE
ssl_version should be negotiated or able to be set

### ISSUE THREAD

**Issue by cakebread** [fritzy/SleekXMPP#11]
When trying to connect to an OpenFire server using 'example.py' the login hangs in xmlstream.py and never times out and never throws an exception:

self.socket.do_handshake()

If I change the SSL type from 'PROTOCOL_TLSv1' to 'PROTOCOL_SSLv3', the login works as expected. Here is the line in xmlstream.py:

self.socket = ssl.wrap_socket(self.socket, ssl_version=ssl.PROTOCOL_TLSv1, do_handshake_on_connect=False)

According to the ssl module documentation, the client should "adapt to the server's protocol version". I'm not sure how that's going to happen given the way self.socket.do_handshake() doesn't throw an exception. Until or unless that is fixed, it would be nice to be able to specify the version. Tested on a git clone from 1/29/2010 using Python 2.6.4.

**Comment by fritzy** [comment]
8 months old, but hey, I thought I'd say this is a good idea. Might be 1.1 though.

**Comment by legastero** [comment]
XMLStream now has the attribute ssl_version which you may set before connecting if you need something other than TLSv1. 

It's not an automated process, but should make things easier now for people working with OpenFire.
