### ISSUE TITLE
Could anyone review my XEP-0080

### ISSUE THREAD

**Issue by skinkie** [fritzy/SleekXMPP#110]
I have not yet 'tested' it myself. But it would be my first 'plugin'.

https://github.com/skinkie/SleekXMPP--XEP-0080-/commit/9f607b64dc9b76059c481b97c52e7dd308ff60cd

Could anyone give some feedback or import it into the develop branch and polish it?

**Comment by legastero** [comment]
I will definitely add this to the small pile of plugins I have waiting for when 1.1 development kicks up again.

**Comment by skinkie** [comment]
> > > from sleekxmpp.plugins.xep_0080 import Geoloc
> > > geoloc = Geoloc()
> > > geoloc.set_lat('0.0')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "sleekxmpp/xmlstream/stanzabase.py", line 1084, in **repr**
> > >     return self.**str**()
> > >   File "sleekxmpp/xmlstream/stanzabase.py", line 1078, in **str**
> > >     top_level=not top_level_ns)
> > > TypeError: tostring() got an unexpected keyword argument 'top_level'

Could you give a hint what the problem is here? I already tried to change from RootStanza to ElementBase

**Comment by skinkie** [comment]
I think I solved it.

**Comment by legastero** [comment]
This has been merged into the develop branch. With the recent pubsub additions, this plugin will also now raise `user_location_publish` events.

**Comment by skinkie** [comment]
Thanks
