### ISSUE TITLE
use_ssl flag not supported by ClientXMPP.connect

### ISSUE THREAD

**Issue by mavwolverine** [fritzy/SleekXMPP#112]
The connect function of ClientXMPP only accepts use_tls. It does not accept use_ssl.
`def connect(self, address=tuple(), reattempt=True, use_tls=True):`
Add it to the list of arguments and pass it forward in 

`return XMLStream.connect(self, address[0], address[1], use_tls=use_tls, reattempt=reattempt)`

New code should be:
`def connect(self, address=tuple(), reattempt=True, use_ssl=False, use_tls=True):`

and

`return XMLStream.connect(self, address[0], address[1], use_ssl=use_ssl, use_tls=use_tls, reattempt=reattempt)`

**Comment by legastero** [comment]
Added in the develop branch, thanks!

**Comment by mavwolverine** [comment]
Welcome!
Glad to help!
