### ISSUE TITLE
JIDs report equal and unequal at the same time

### ISSUE THREAD

**Issue by TheGurke** [fritzy/SleekXMPP#113]
Minimal broken example:

<pre>
>>> from sleekxmpp.xmlstream.jid import JID
>>> JID("name@domain.org") == JID("name@domain.org")
True
>>> JID("name@domain.org") != JID("name@domain.org")
True
</pre>

Solution: Explicitly implement unequal method in xmlstream/jid.py

<pre>
def __ne__(self, other):
        """
        Two JIDs are considered unequal if they are not equal.
        """
        return not self == other
</pre>

**Comment by legastero** [comment]
Thanks! This is fixed in the develop branch and will make it in to RC3 today.

**Comment by TheGurke** [comment]
Wow that was fast, thanks ;)
