### ISSUE TITLE
XEP-0050 plugin does not parse forms on client side

### ISSUE THREAD

**Issue by coffeeowl** [fritzy/SleekXMPP#119]
When command provider sends a form back as a response for command execution query, payload for session is set to None, I would expect it to contain a form sent by a command provider. And I can see a form in iq stanza on client side, on provider side forms work nicely and I can access data in session["payload"].

**Comment by macdiesel** [comment]
You can get the form sent back from the provider from:
response['command']['form']['values']

and the session id from:
response['command']['sessionid']

Are you claiming that this info is not there? or that it should be moved somewhere else?

**Comment by coffeeowl** [comment]
I see... I am new to SleekXMPP and was a little bit confused, on provider side you specify your form in 'payload', so, I was working under assumption that on client side 'payload' will contain this form.
response['command']['form']['values'] is actually contain values.

**Comment by coffeeowl** [comment]
Actually, it doesn't work in some cases. My server component sends probes to known clients on session startup and when client reports its presence back, it invokes adhoc command on a client, this happens inside 'presence_available' handler. The command itself goes fine and I receive iq with a form, but I can't access it through iq['command']['form'] - it is empty. Out of curiosity I have inserted the same command inside one of command my component provides and then invoked it manually as a part of component's command, this way it works. Are there any restrictions on where I can run commands and expect forms back?

To clarify this a little bit here is some code.
Component's presence handler:

```
def _on_node_avail(self, presence):
    syslog(LOG_NOTICE, "node online: %s, status %s" %
           (presence["from"], presence["status"]))
    try:
        self.db.updateNode(str(presence["from"]), {"online": True})
        # Here it doesn't work, iq is all right, but form is empty
        InfoCommandClient(self, presence["from"])
    except Exception, e:
        syslog(LOG_ERR, "error while setting node online, %s" % e)
```

And here I have inserted it inside a command component provides, this way it works.

```
def _cmd_handle_form(self, payload, session):
    try:
        # here is some command specific code

        # Here I have inserted it to test how it works (and it works)
        InfoCommandClient(self, targetJid)

        # some other code
        session["conf"] = conf
        session["payload"] = form
        session["has_next"] = False
        session["next"] = None
        syslog(LOG_INFO,
               "command 'getconf' from %s completed" % session["from"])
    except Exception, e:
        syslog(LOG_ERR, "error while completing 'getconf' command, %s" % e)
        session["notes"] = [
            ("error", "cannot process 'getconf' command, %s" % e)
            ]

    return session
```

InfoCommandClient itself is trivial, sends form, receives form.

**Comment by macdiesel** [comment]
What does your implementation of InfoCommandClient look like?  You did not include it in your example but it might be the most important piece of the code we would need to look at.

Are you sending the command via the xep_0050 method send_command?  There is some code in there that builds the correct stanza object.  

ex:
response = self.xmpp['xep_0050'].send_command(jid=jid, node='my_command', action='next', payload=form, sessionid=sid)

**Comment by legastero** [comment]
The issue here is a bit of asymmetry between the user/provider sides. The xep-50 plugin is registering stanza plugins for the Command stanza as they are used, but the client side might not be given a form to trigger the registration before receiving one in a command.

Since data forms are pretty much the only payload used for commands (but not necessarily), I've gone ahead and fixed this by preregistering the data form stanza plugin so that the client always recognizes the form. 

I've typically not run into this issue (and thus hadn't noticed the bug) for two reasons:
1. I usually know what the initial form will be so I've just created a form and filled in the answers and sent that. After that, everything works as expected.
2. There was a memory related bug which caused stanza plugins to be registered for most stanzas, not just the parent stanza listed in the registration call. Therefore, the form stanza plugin was always available in commands. Since that bug was fixed recently, that is no longer the case and forms must be explicitly registered.

You can either use the develop branch, or just add a `register_stanza_plugin(Command, Form)` call before you start the command.

**Comment by coffeeowl** [comment]
macdiesel: it is mostly the same as in ad_hoc examples. And as it works inside another command as I have described before, I think I know why it behaves this way, because in the second case this command works inside another command for which data forms are already available.

So, I'll try what legastero suggested and then report back.

legastero: I prefer to use forms supplied by another side because they can contain some extra information, like hidden fields, I am not sure are they prone to change in ejabberd, for instance, or not, so better safe than sorry.
By the way, there is another small issue - XEP-0133 states that it is based on XEP-0050 but it doesn't work with current XEP-0050 plugin implementation. At least ejabberd does not supply action tag in a stanza and respond with "400 modify" if action element is present in a client's response. I have to use send_command manually, to strip away "action" tag, but I think it is mostly for internal use, as it exposes session handling to SleekXMPP user. I am not complaining here, just a note.

And I hope you don't mind if I'll send you a diff for ad_hoc examples after my experimentation? I think the examples can be extended a little bit.
