### ISSUE TITLE
Bug in Roster.getItems()

### ISSUE THREAD

**Issue by DavidLo** [fritzy/SleekXMPP#13]
This method don't work, and this line is the cause : 

items[JID(itemxml.get('jid'))] = item

Because variables are assigned by reference, the dictionnary is full of the last item values.

I've used this workaround with the help of copy module :

items[JID(itemxml.get('jid'))] = copy.copy(item)

Maybe there are better solutions.

**Comment by fritzy** [comment]
fixed
