### ISSUE TITLE
Support for M$ custom Oauth

### ISSUE THREAD

**Issue by Pablo2m** [fritzy/SleekXMPP#134]
Hello
Here is a basic description
http://msdn.microsoft.com/en-us/windowslive/hh561460

**Comment by legastero** [comment]
This is in develop branch now.

It does require a few special considerations to make it work:
1. Bring your own access token. Doing the OAuth dance properly effectively requires a browser, and that goes beyond SleekXMPP's scope.
2. Use the access token as the password when initializing ClientXMPP
3. Use `user@messenger.live.com` as the JID. (This will be reset by the server during session binding, but we need a JID using the MSN server and a username portion to prevent dropping to anonymous authentication.)
4. Be sure to register the `xep_0199` (ping) plugin, and configure it to use keepalives. The MSN server is currently terminating connections that have been idle for only one or two minutes.
5. If `dnspython` is not installed, you will need to manually connect to `xmpp.messenger.live.com`.

``` python
    xmpp.register_plugin('xep_0199', {'keepalive': True, 'frequency': 60})
```
