### ISSUE TITLE
Error reading from XML stream after 'no_auth' event

### ISSUE THREAD

**Issue by rhcarvalho** [fritzy/SleekXMPP#139]
If we try to login with an invalid jid/password, ClientXMPP will try all mechanisms and eventually fail:

```
sleekxmpp/features/feature_mechanisms/mechanisms.py:129
ERROR    No appropriate login method.
sleekxmpp/xmlstream/xmlstream.py:1192
ERROR    Error reading from XML stream.
```

The second error line is unexpected.

_Using current HEAD from the development branch (25f87607aab0de024be90d6e6d0e96c19e827f49)._

**Comment by legastero** [comment]
This is expected since Google simply terminates the stream without sending a closing `</stream>` tag.

**Comment by rhcarvalho** [comment]
Ok, right. I should have said "_I didn't expect the second error line_".
