### ISSUE TITLE
xep_0060 plugin broken

### ISSUE THREAD

**Issue by zhudav** [fritzy/SleekXMPP#14]
All the iq.get('id') calls in the class throws exceptions.  As far as I can tell, the get() on Iq objects does not take any parameters and it is overriding the get() in ElementBase which does take a key param.

**Comment by fritzy** [comment]
fixed... rewriting this plugin to use the new stanza objects though, so I'm leaving this open

**Comment by sezuan** [comment]
In 0dcbe92d1e49a9f009b39c39150307e3c15c9f9b the get,set,.. methods in the iq class have been removed. What's the proper way to get the result? result['type'] seems not to work.

**Comment by zhudav** [comment]
Try result.get('type'), that seems to work for me.

**Comment by sezuan** [comment]
thanks! it works :)

**Comment by fritzy** [comment]
fixed
