### ISSUE TITLE
Poor Handling of SSL Verification Failures

### ISSUE THREAD

**Issue by teisenbe** [fritzy/SleekXMPP#144]
If the ssl module fails to verify the server's certificate, it raises an SSLError that is never caught and never propagated to the user.  This can be easily triggered by creating an instance of ClientXMPP and setting its ca_certs attribute to the name of a file containing a cert that does not match the server that is being connected to.

**Comment by legastero** [comment]
This is being worked on now, in addition with pulling in pyOpenSSL/pyasn1 to do proper certificate validation.
