### ISSUE TITLE
error in XMLStream: remove_stanza 

### ISSUE THREAD

**Issue by leopay** [fritzy/SleekXMPP#146]
as self.__root_stanza is a list, we  cannot use like this

```
del self.__root_stanza[stanza_class]
```

**Comment by leopay** [comment]
maybe we could use like this

```
self.__root_stanza.remove(stanza_class)
```

**Comment by legastero** [comment]
Yes, that would be a leftover bit of an experimental change that got merged in sometime. Should be fixed in develop now.

**Comment by leopay** [comment]
these is still a bug

```
del self.__root_stanza.remove(stanza_class)
```

should change to 

```
self.__root_stanza.remove(stanza_class)
```

**Comment by legastero** [comment]
And that's what I get for trying to do things quickly first thing in the morning.
