### ISSUE TITLE
I got DEBUG Could not acquire lock when call disconnect()

### ISSUE THREAD

**Issue by leopay** [fritzy/SleekXMPP#147]

**Comment by leopay** [comment]
```
Could not acquire lock
```

how to avoid this.

**Comment by legastero** [comment]
Did the client disconnect? If so, there is nothing to avoid. That statement just means the statemachine was in use by another thread when it first tried to switch to the disconnected state.

**Comment by leopay** [comment]
ths，I see

**Comment by legastero** [comment]
Actually, after going through and looking some more, disconnect() had a very short wait time for acquiring the lock. I've bumped that up to 2 seconds in the develop branch, so that should make those statements go away.
