### ISSUE TITLE
When the server disconnects, it makes the client disconnect and never try to reconnect

### ISSUE THREAD

**Issue by vcarel** [fritzy/SleekXMPP#149]
I'm using SleekXMPP connected to Ejabberd as an external component.

During the application life, we will have sometimes to restart Ejabberd, either because it may crash, or either because we will need to update it.
However, when we attempt a restart, we noticed that it makes the SleekXMPP client stop, with the following logs :

```
ERROR : Error reading from XML stream.
ERROR : no element found: line 1, column 164
Traceback (most recent call last):
  File "/home/neko/src/neko/DEV/local/lib/python2.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1150, in _process
    if not self.__read_xml():
  File "/home/neko/src/neko/DEV/local/lib/python2.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1186, in __read_xml
    for event, xml in ET.iterparse(self.filesocket, (b'end', b'start')):
  File "<string>", line 86, in next
ParseError: no element found: line 1, column 164
DEBUG : SEND (IMMED): </stream:stream>
DEBUG : Waiting for </stream:stream> from server
DEBUG :  ==== TRANSITION connected -> disconnected
DEBUG : Quitting Scheduler thread
```

What happens is that the XMLStream.process() method, which loops on listening to the server stanza, catchs a ParseException and then rethrow it again unhandled.

This issue is very similar to #145 and #101, in the difference that the exception is not the same.

I checked out the corrections of those two tickets and I think it's going in the wrong direction. In no case the client should stop because something went wrong with the server. The reason does not matter, unless the error is caused by the client itself...

**Comment by legastero** [comment]
Which version of Sleek are you using? Develop or the 1.0 release on PyPI?

**Comment by vcarel** [comment]
The 1.0 release, but I can still the issue in the develop branch.

**Comment by jpcaruana** [comment]
Hi,
I aggre with @vcarel  's  conclusion : the client shouldn't crash in theses cases.

**Comment by legastero** [comment]
@jpcaruana I certainly agree that it shouldn't crash.

It is supposed to disconnect and reconnect in these situations\* (and later when we add XEP-0198 support, resume the session). 

@vcarel Is the reconnect not happening? Or did you set self.auto_reconnect to False?
- goes back to read RFC 6120 again to double check what is supposed to happen

**Comment by vcarel** [comment]
The reconnect is not happening because of the ParseException. It is caught, but rethrown in the except block...
auto_reconnect is set to true.

Regarding the RFC 6120, I don't think it says the client has to crash whenever there's a stream error ;-)

**Comment by vcarel** [comment]
OMG, I was not looking at the right exception ! Actually that is caught as a SyntaxError. In the catch block, there was a 'shutdown = True' which had already been removed in development.

I'm closing the issue : my apologies for the inconvenience.

**Comment by legastero** [comment]
No worries :)

It's always good to go back and review things, and I noticed during this that I should add in some stream error responses in some cases to be compliant with RFC 6120.
