### ISSUE TITLE
Setup is missing tostring26 and tostring

### ISSUE THREAD

**Issue by legastero** [fritzy/SleekXMPP#15]
The packages list in setup.py does not include xmlstream/tostring or xmlstream/tostring26

**Comment by legastero** [comment]
The packages were included separately from the main package list, but have been commented out in yesterday's commit 58375955a9b832356ba68cc1f9ecb3bc274b6922

**Comment by fritzy** [comment]
took a full reinstall to see what was going on here -- fixed
