### ISSUE TITLE
set_payload does not work with ElementTree

### ISSUE THREAD

**Issue by fabianp** [fritzy/SleekXMPP#156]
I would expect the following to work both with ElementTree and cElementTree, as ElementTree is a superset of cElementTree. Instead, it only works for cElementTree.

```
In [14]: iq = xmpp.make_iq_set(ito='user1@localhost')

In [15]: iq.set_payload(ElementTree.fromstring('<body></body>'))
```

issue seems to be in the line `type(item) == XML_TYPE`. I would suggest to check for capabilities (hasattr) instead of type equality to be robust to other containers and derived classes.

**Comment by legastero** [comment]
Generally, I agree that the `hasattr` approach is better; however, in this case we really do need to differentiate on type.

While ElementTree and cElementTree have the same API, instances of each are not compatible with each other. I.e, appending an ElementTree object to a cElementTree object fails with a type error.

When creating new XML objects directly, I recommend using the pattern:

```
from sleekxmpp.xmlstream import ET

xml = ET.fromstring('<foo />')
```

This will ensure that the same version is always used.

**Comment by fabianp** [comment]
oh, thanks for the reply. There are plenty of references on the doc to ElementTree and I thought they refered to xml.etree. I see now they refer to sleekxmpp.xmlstream and code works fine.

Closing this
