### ISSUE TITLE
TypeError: cannot create weak reference to 'weakref' object

### ISSUE THREAD

**Issue by leopay** [fritzy/SleekXMPP#159]
in xmlstream/stanzabase.py

```
#: A :class:`weakref.weakref` to the parent stanza, if there is one.
#: If not, then :attr:`parent` is ``None``.
self.parent = None
if parent is not None:
    self.parent = weakref.ref(parent)
```

if parent is a weakref object, this could cause

`TypeError: cannot create weak reference to 'weakref' object`

**Comment by legastero** [comment]
Not an anticipated use case, but supplying weakrefs as parent pointers works now. Thanks!
