### ISSUE TITLE
Roster not updated correctly in ClientXMPP._handleRoster

### ISSUE THREAD

**Issue by Belgabor** [fritzy/SleekXMPP#16]
The line that's supposed to do the update does not work. Fix:

```
def _handleRoster(self, iq):
    for jid, data in iq['roster']['items'].iteritems():
        if not jid.bare in self.roster:
            self.roster[jid.bare] = {'groups': [], 'name': '', 'subscription': 'none', 'presence': {}, 'in_roster': True}
        self.roster[jid.bare].update(data)
    if iq['type'] == 'set':
        self.send(self.Iq().setValues({'type': 'result', 'id': iq['id']}).enable('roster'))
    self.event("roster_update", iq)
```

**Comment by dlenski** [comment]
Yeah, I just ran into this too... it's a very odd bug!  I changed the code around slightly:

```
def _handleRoster(self, iq):
            items = iq['roster']['items']
    for jid, info in items.items():
        if not jid.bare in self.roster:
            self.roster[jid.bare] = {'groups': [], 'name': '', 'subscription': 'none', 'presence': {}, 'in_roster': True}
        self.roster[jid.bare].update(info)
    if iq['type'] == 'set':
        self.send(self.Iq().setValues({'type': 'result', 'id': iq['id']}).enable('roster'))
    self.event("roster_update", iq)
```

And it _still_ doesn't work!  Every person on the roster gets the name of the _last_ person on the roster.  Bizarre!!!  Could this be a concurrency issue with the XML parsing?  I don't really understand how this happens, but it does.

If you do debug.logging(str(iq)), everything looks reasonable.  But if you do debug.logging(str(iq['roster']['items'])), then you get a nonsensical dictionary in which all the roster items have the same name.

????

**Comment by fritzy** [comment]
that was a doozy. fixed.
