### ISSUE TITLE
ClientXMPP does not shut down cleanly

### ISSUE THREAD

**Issue by Belgabor** [fritzy/SleekXMPP#17]
If you quit by pressing Ctrl+C, the program hangs (at least the example does). This appears to be because the send thread does not quit. Replacing the while clause in XMLStream._sendThread (while True:) with

```
    while self.run or not self.sendqueue.empty():
```

appears to fix the issue

**Comment by Belgabor** [comment]
Seems like that is not enough and the safety clause I added can still keep it from shutting down. Should probably be just

```
while self.run:
```

**Comment by fritzy** [comment]
fixed
