### ISSUE TITLE
Python3 exception handling compatibility issue

### ISSUE THREAD

**Issue by seb-m** [fritzy/SleekXMPP#173]
In the develop branch this exception handling is not compatible with Python3 interpreters https://github.com/fritzy/SleekXMPP/blob/develop/sleekxmpp/plugins/xep_0065/proxy.py#L321

**Comment by legastero** [comment]
Thanks! The xep-0065 plugin is brand new, so if you have any other feedback for it it is greatly appreciated.

**Comment by seb-m** [comment]
Hi thanks! and btw you're doing an awesome work on this project!

**Comment by SeyZ** [comment]
Thanks for the issue and the fix !
