### ISSUE TITLE
ClientXMPP.make_message creating invalid Messages?

### ISSUE THREAD

**Issue by muchadhesion** [fritzy/SleekXMPP#176]
Hi,

I'm having trouble persuading ClientXMPP.make_message to create a valid Message.

In the ipython output below, I end up with a message with 2 html bodys.  see [14]
...Of which only the first (empty one) is propagated to m["body"], see [15]

What am I doing wrong?

```
$ipython
In [1]: import sleekxmpp as s

In [12]: c = s.ClientXMPP( "person1@xmpp.example.com", "password")

In [13]: m = c.make_message( "person1@xmpp.example.com", "BODY", None, "chat", None, "person2@xmpp.example.com", None)

In [14]: m
<message to="person1@xmpp.example.com" type="chat" xml:lang="en" from="person2@xmpp.example.com"><body /><body>BODY</body></message>

In [15]: m.values
{'body': u'', u'lang': u'en', 'from': person2@xmpp.example.com, 'mucnick': '', 'mucroom': '', 'to': person1@xmpp.example.com, 'type': 'chat', 'id': u'', 'subject': u''}
```

**Comment by legastero** [comment]
Hi,

Which version are you using? 1.1.7 should have corrected that issue.

-- Lance

**Comment by muchadhesion** [comment]
Wow.  Thanks for the swift response.
I'm on 1.1.5 I'll update.
Many thanks.
