### ISSUE TITLE
Circular reference in stanzabase.py causing memory leak

### ISSUE THREAD

**Issue by lboynton** [fritzy/SleekXMPP#18]
After using SleekXMPP for a bot, we noticed that it was leaking memory, and believe we have narrowed it down to at least this circular reference in the ElementBase constructor in stanzabase.py:

self.attrib = self # backwards compatibility hack

We are still monitoring memory usage, but so far unsetting this variable has appeared to improve the memory usage for us.

**Comment by fritzy** [comment]
fixed -- attrib is now a @property get function returning self

**Comment by lboynton** [comment]
Thanks!
