### ISSUE TITLE
SleekXMPP should always prefer SRV records, if available

### ISSUE THREAD

**Issue by horazont** [fritzy/SleekXMPP#183]
Hi,

I just ran into a problem with a SleekXMPP based application which was unable to connect after I cleaned up my zone file yesterday. I removed all records which were not neccessary and added SRV records for the xmpp services. So the following records exist (verify with dns querier of your choice):

`SRV _xmpp-client._tcp.hub.sotecware.net -> 0 0 5222 sotecware.net.`

However, hub.sotecware.net has neither an A nor an AAAA record, which is intended. SleekXMPP fails to connect to the host, and the following is found in the debug log:

```
[…]
DEBUG    DNS: Querying hub.sotecware.net for AAAA records.
DEBUG    DNS: Error retreiving AAAA address info for hub.sotecware.net.
DEBUG    DNS: Querying hub.sotecware.net for A records.
DEBUG    DNS: Error retreiving A address info for hub.sotecware.net.
DEBUG    No remaining DNS records to try.
DEBUG    Waiting 1.972129000198605 seconds before connecting.
DEBUG    DNS: Querying hub.sotecware.net for AAAA records.
DEBUG    DNS: Error retreiving AAAA address info for hub.sotecware.net.
DEBUG    DNS: Querying hub.sotecware.net for A records.
DEBUG    DNS: Error retreiving A address info for hub.sotecware.net.
DEBUG    No remaining DNS records to try.
DEBUG    Waiting 3.182282399058604 seconds before connecting.
[…]
```

It seems like SleekXMPP does not try to use SRV records to find the correct FQDN to connect to, which is a violation of [XMPP CORE, 3.2.1 Preferred Process: SRV Lookup](http://xmpp.org/rfcs/rfc6120.html#tcp-resolution-prefer).

I am using SleekXMPP git:fbad22a and just tried with origin/master, which has the same problem. Adding 88.198.247.171 for hub.sotecware.net to the /etc/hosts makes sleekxmpp connect fine.

pidgin / libPurple also connect fine to hub.sotecware.net without A/AAAA records available.

cheers,
Jonas

**Comment by legastero** [comment]
It looks like you don't have dnspython installed, which is required for Sleek to do SRV resolution.

**Comment by horazont** [comment]
Ah thanks. In that case it would be cool to have that in the log as a Warning maybe?
