### ISSUE TITLE
The package in PyPi is not the latest?

### ISSUE THREAD

**Issue by ayanamist** [fritzy/SleekXMPP#189]
While it's 1.1.8 in PyPi, it's 1.1.9 here. So why don't you update it? My build script depends on pip requirements.txt, and a full download is less readable than plain "sleekxmpp=1.1.9".

**Comment by legastero** [comment]
Wow, can't believe I forgot to do that. PyPI is updated now.

**Comment by legastero** [comment]
Also, 1.1.10 is out now, and is up on PyPI too.
