### ISSUE TITLE
htmlim.py / XEP-0071

### ISSUE THREAD

**Issue by cakebread** [fritzy/SleekXMPP#19]
I was looking for a way to send HTML without it being escaped, and it looks like XEP-0071 is what I'd need to implement. While browsing the source I came across htmlim.py which seems to be a good start. Is this an XEP-0071 implementation, and if so, how can I use it to send HTML in a message?

P.S. Is there a mailing list or someplace else to ask questions like this?

**Comment by fritzy** [comment]
Take a look at http://wiki.github.com/fritzy/SleekXMPP/stanzas-message (I just added it to the docs).  Also .makeMessage and .sendMessage have an mhtml option that may be a cElement.Element()
