### ISSUE TITLE
XMLStream _handle_connected broken by ClientXMPP

### ISSUE THREAD

**Issue by jlovinger-nullsquared** [fritzy/SleekXMPP#199]
Both XMLStream and Client XMPP **init**() register self._handle_connected for the "connected" event. Likewise they both define _handle_connected(). Unfortunately ClientXMPP._handle_connected takes precedence and is added into the handler table _twice_. Net result is that the session timeout check from XMLStream._handle_connected is never inserted into the scheduler to detect a session timeout.

**Comment by legastero** [comment]
Good catch! Both handlers are now renamed, so that should be fixed now.
