### ISSUE TITLE
UTF-8 characters don't work in 2.6

### ISSUE THREAD

**Issue by fritzy** [fritzy/SleekXMPP#2]
I need to do a conditional import to get utf-8 chars to work in 2.6.  For now, 3.x is the only supported way to run SleekXMPP until this is fixed.

**Comment by fritzy** [comment]
Mostly fixed... still testing...

**Comment by cakebread** [comment]
Is there a branch known to work with Python 2.6 we can use until this is fixed?

**Comment by fritzy** [comment]
Fixed via setting the defaultencoding.
