### ISSUE TITLE
sleekxmpp reloads the sys module

### ISSUE THREAD

**Issue by pitrou** [fritzy/SleekXMPP#202]
basexmpp.py contains this ugly hack:

```
# In order to make sure that Unicode is handled properly
# in Python 2.x, reset the default encoding.
if sys.version_info < (3, 0):
    reload(sys)
    sys.setdefaultencoding('utf8')
```

This means any customization done to the sys module prior to importing sleekxmpp will be silently lost.
(not to mention that changing the default encoding is very bad practice).

**Comment by legastero** [comment]
This was actually just changed yesterday to not reload the sys module. See issue #201

**Comment by legastero** [comment]
I do still want to get rid of the setdefaultencoding hack, but that's a good first step.

The end solution will probably be gratuitous use of `from __future__ import unicode_literals` everywhere and making that method available so end users can call it if they actually want it, or not if they know they only pass Unicode data to Sleek.

**Comment by pitrou** [comment]
> This was actually just changed yesterday to not reload the sys
> module. See issue #201

Ah, thank you.
