### ISSUE TITLE
Too many metadata removal in XEP-0004 dataforms

### ISSUE THREAD

**Issue by Schnouki** [fritzy/SleekXMPP#218]
9b7ed73f introduced the following change: "Setting the form type to 'submit' will remove extra meta data from the form fields, leaving just the 'var' and 'value'".

It's wrong to remove the fields 'type'; see http://xmpp.org/extensions/xep-0004.html#examples-config for examples.

**Comment by legastero** [comment]
XEP-0004, section 3.2 says: For data forms of type "submit", inclusion of the 'type' attribute is OPTIONAL, since the form-processing entity is assumed to understand the data types associated with forms that it processes.

**Comment by Schnouki** [comment]
You're right. The issue I'm having is actually completely different; I'll open a new issue to describe it. Thanks for your reply.
