### ISSUE TITLE
Service Discovery stanzas

### ISSUE THREAD

**Issue by fritzy** [fritzy/SleekXMPP#22]
Service Discovery needs stanzas written for it's namespaces.

**Comment by legastero** [comment]
I've made a new (backwards compatible) version of xep_0030 that uses stanza objects. I'm working on unit tests for it, but manually testing everything with Psi worked OK.

File is at: http://github.com/legastero/SleekXMPP/blob/master/sleekxmpp/plugins/xep_0030.py

**Comment by legastero** [comment]
Did a lot of cleaning up in my repo, file is now on a xep_0030 branch: http://github.com/legastero/SleekXMPP/blob/xep_0030/sleekxmpp/plugins/xep_0030.py

**Comment by fritzy** [comment]
will merge this into develop and try it out

**Comment by fritzy** [comment]
this is in the experimental branch, and I'll audit it

**Comment by fritzy** [comment]
I need to add better dynamic listing in the plugin.

**Comment by fritzy** [comment]
official
