### ISSUE TITLE
Failed to import _strptime because the import lockis held by another thread

### ISSUE THREAD

**Issue by rasathus** [fritzy/SleekXMPP#231]
sleekxmpp is being used as part of another module, but during checks for certificate expiry I'm getting a stack trace for an import error ...

`ImportError: Failed to import _strptime because the import lockis held by another thread.`

The full trace and surrounding logs are available in the Gist below.

[Gist](https://gist.github.com/rasathus/5467290)

This appears to be related to [python bug 7980](http://bugs.python.org/issue7980) to do with the thread safety of strptime

**Comment by legastero** [comment]
If you still have import errors, reopen. Threading issue solutions are always iffy.

**Comment by rasathus** [comment]
Thanks
