### ISSUE TITLE
Error processing stream handler: IBB Open

### ISSUE THREAD

**Issue by SecurityForUs** [fritzy/SleekXMPP#237]
I'm able to send and transfer files to and from an SleekXMPP client to myself, but when I try to do the same between SleekXMPP clients, I get this:

``` python
Traceback (most recent call last):
  File "/home/eric/.virtenvs/sysbotxmpp/lib/python2.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1645, in _event_runner
    handler.run(args[0])
  File "/home/eric/.virtenvs/sysbotxmpp/lib/python2.7/site-packages/sleekxmpp/xmlstream/handler/callback.py", line 76, in run
    self._pointer(payload)
  File "/home/eric/.virtenvs/sysbotxmpp/lib/python2.7/site-packages/sleekxmpp/plugins/xep_0047/ibb.py", line 184, in _handle_open_request
    raise XMPPError(etype='modify', condition='not-acceptable')
XMPPError
```

I'm using v1.2 from the Git repo here.  I have event handlers for both IBB_Stream_Data and IBB_Stream_Start,

There's no IQ error, but then happens on this line of my code:

``` python
stream = self.xmpp['xep_0047'].open_stream(who, sid=sid)
```

Here's the IQ data that was received:

``` python
<iq to="server_bump@localhost/192.168.0.6" type="result" id="4b9c27c1-9b51-41b4-a4ae-19cab37c74ff-6" from="server_free@localhost/192.168.0.6">
<si xmlns="http://jabber.org/protocol/si">
<feature xmlns="http://jabber.org/protocol/feature-neg">
<x xmlns="jabber:x:data" type="submit">
<field var="stream-method">
<value>http://jabber.org/protocol/bytestreams</value>
</field>
</x>
</feature>
</si>
</iq>
```

Is this happening because IBB isn't being reported as a stream method?  If so how can I have the client specify IBB as a stream method?

**Comment by legastero** [comment]
This is happening because Sleek supports both IBB and SOCKS5 bytestreams. And when given the choice between the two, it will prefer SOCKS5. So trying to open an IBB stream after negotiating fails, because the other client is expecting a SOCKS5 stream.

If you must not use SOCKS5, then use:

```
del xmpp['xep_0095']._methods['http://jabber.org/protocol/bytestreams']
```

And that will stop Sleek from both offering and requesting SOCKS5.

**Comment by SecurityForUs** [comment]
Would I put that in my ClientXMPP `__init__` or somewhere else?  Or, is there a way to change the order where IBB is first?

**Comment by legastero** [comment]
Yeah. Before you try negotiating a stream. Right now the ordering is hard coded here: https://github.com/fritzy/SleekXMPP/blob/develop/sleekxmpp/plugins/xep_0095/stream_initiation.py#L104

**Comment by SecurityForUs** [comment]
Thanks; is there a way to try and change that so it's more modular, or return both at least?

**Comment by legastero** [comment]
Ok, just pushed a patch to develop. You can now just do:

xmpp['xep_0095'].unregister_method('http://jabber.org/protocol/bytestreams')

Edit: changed namespace to the one you're actually wanting to remove

**Comment by legastero** [comment]
As for returning both, no. The whole point is that you return the one method that you wish to use out of the options the other client is offering.

**Comment by SecurityForUs** [comment]
Thanks :D  Definitely works now! Hehe

**Comment by pythonshiva** [comment]
Where should i push this line ?

xmpp['xep_0095'].unregister_method('http://jabber.org/protocol/bytestreams')
