### ISSUE TITLE
Iq object missing the function findall

### ISSUE THREAD

**Issue by zhudav** [fritzy/SleekXMPP#24]
Not sure what happened, but Iq object no longer has this method?  This breaks a lot of the code...

**Comment by zhudav** [comment]
Ok, found and fixed.  need to add this to stanzabase.py:

def findall(self, xpath):
     return self.xml.findall(xpath)

Does anyone else test this stuff?!!

**Comment by rroemhild** [comment]
Wonderful! I just run into the same issue.
Works for me. Thx!

**Comment by fritzy** [comment]
Fixed in master.  Thanks guys.
