### ISSUE TITLE
Working sample

### ISSUE THREAD

**Issue by marimuthuvm** [fritzy/SleekXMPP#258]
Does anyone have a working sample code for the prebind with non AMD?

**Comment by legastero** [comment]
What do you mean by "non AMD?"

**Comment by marimuthuvm** [comment]
Yeah exactly.

**Comment by marimuthuvm** [comment]
The request is getting aborted when i use non_amd.html

```
The request is going with same sid,jid,
RiD is varying
But the request is getting aborted and re requesting it again
```

POST http://staging-xmpp.by-esn.com:5280/http-bind/

200 OK 1.79s strophe.js (line 2969)
POST http://staging-xmpp.by-esn.com:5280/http-bind/

Aborted 1m 6s strophe.js (line 2969)
POST http://staging-xmpp.by-esn.com:5280/http-bind/

200 OK 498ms strophe.js (line 2969)
POST http://staging-xmpp.by-esn.com:5280/http-bind/

Aborted 1m 6s strophe.js (line 2969)
POST http://staging-xmpp.by-esn.com:5280/http-bind/

200 OK 357ms strophe.js (line 2969)
POST http://staging-xmpp.by-esn.com:5280/http-bind/

My code is follows

$.getJSON('converse.php', function (data) {

  converse.initialize({
            auto_list_rooms: false,
            auto_subscribe: false,
            bosh_service_url: 'http://staging-xmpp.by-esn.com:5280/http-bind/', // Please use this connection manager only for testing purposes
            hide_muc_server: false,
            i18n: locales.en, // Refer to ./locale/locales.js to see which locales are supported
            prebind: true,
            sid:data.sid,
            jid:data.jid,
            rid:data.rid, 
            show_controlbox_by_default: false,
            xhr_user_search: false
            });
            connection = new Strophe.Connection('http://staging-xmpp.by-esn.com:5280/http-bind/');
            connection.attach(data.jid, data.sid, data.rid, function () {
                converse.onConnected(connection);
            });

```
    });
```

username:diwakarreddy@staging-xmpp
password: 12345678

converse.php. will give you the sid,rid,jid

Correct me if am wrong?

**Comment by legastero** [comment]
Do you mean to be working with the https://github.com/strophe/strophejs repo? I don't see where you're using Python and SleekXMPP.
