### ISSUE TITLE
Message Reply

### ISSUE THREAD

**Issue by legastero** [fritzy/SleekXMPP#26]
It is preferable for message stanzas to be sent without a 'from' attribute because an XMPP server can either simply replace an incorrect or missing 'from' value, or reject the message entirely. A correct 'from' value is the full JID of the sending agent.

GTalk servers in particular are strict in that 'from' values that are just the bare JID are rejected.

Thus, using the reply method on message objects (which just swaps the 'to' and 'from' attributes) fails to correctly send messages in all cases when the message being replied to was sent only to a bare JID.

A good solution would be to simply drop the 'from' attribute when creating a reply.

**Comment by fritzy** [comment]
I'm ruling out that solution for Components. Perhaps that's a good default behavior, and components can pass an option to keep this from happening.

**Comment by hildjj** [comment]
Pushed a patch (66e92c6..d70a6e6) which adds an is_component attribute, then checks it in reply().

**Comment by fritzy** [comment]
merged hildjj's patch
