### ISSUE TITLE
Release policy

### ISSUE THREAD

**Issue by seocam** [fritzy/SleekXMPP#260]
Does the project have any milestone? When new releases are coming or should I just use master as the stable version?

**Comment by rmoch** [comment]
:+1:

**Comment by kxepal** [comment]
+1 
the latest available release is very out of dated. it's time to make a new one (:

@legastero do you need any help with testing, cleanup, docs, new missed feature - with all that blocks possibility to create a new `1.1.12` (or even `1.2.0` since there are a lot of changes had done) tag?

**Comment by legastero** [comment]
1.2.0 released!

**Comment by seocam** [comment]
:+1:

**Comment by kxepal** [comment]
Woo-hoo! Thanks @legastero !
