### ISSUE TITLE
memory problem

### ISSUE THREAD

**Issue by BaseMax** [fritzy/SleekXMPP#268]
i have extended echobot and mucbot to fit my requirement i am running multiple instance of these bots just around 5 of mucbot(i need to run more in hundreds) and 1 of echobot after some hours these all go offline or not responding to commands etc then i checked server ram its full . and i ran killall python  its all gone away ram is free. its a 512mb ram vps

can anyone help me to fix this problem?

**Comment by hwkns** [comment]
Without seeing your code, there isn't much anyone can do to help.

You might find StackOverflow to be more helpful for this sort of thing, as you haven't found a specific issue with SleekXMPP yet.
http://stackoverflow.com/questions/1435415/python-memory-leaks

**Comment by bear** [comment]
closing - please reopen if 1) this is still happening and 2) you can give more details of the version of Python being used and you have tried it with the latest SleekXMPP.

also - to be honest, trying to run more than a handful of bots in a 512mb vps is only going to lead to headaches, heartbrakes and a desire to eat chocolate chip cookie dough ice cream ...
