### ISSUE TITLE
Delete Event Handlers

### ISSUE THREAD

**Issue by legastero** [fritzy/SleekXMPP#27]
There is currently no provided way to remove event handlers once they have been added.

Why remove event handlers? For some applications (like one I'm working on) it is necessary for the program to change 'roles' and respond to different types of events. One solution would be to add extra state information to each handler that will be turned on and off. However, that can get messy quickly, and having one place that can set the proper event handlers can be simpler.

I have a patch available at http://github.com/legastero/SleekXMPP/commit/ce7ff9f4539d09cc91bf140606f3e394c7df3794 that implements such a method for BaseXMPP.

**Comment by fritzy** [comment]
pulled.  Thanks for the patch! I'll look through it and add some tests to make sure it doesn't break anything.
