### ISSUE TITLE
post_init is not called when loading a plugin with registerPlugin

### ISSUE THREAD

**Issue by legastero** [fritzy/SleekXMPP#28]
There are two options for loading plugins: register_plugins and registerPlugin. The first option is for loading all plugins at once, and after it does so (by using registerPlugin to load each plugin) it calls post_init on each plugin. However, if only registerPlugin is used, post_init is not called. 

Since post_init is intended for cross-plugin interaction, this can cause trouble with registering service discovery features.

I've made a patch to let registerPlugin call post_init, depending on if a flag passed to it is set. This way register_plugins can delay calling post_init until after all plugins have been loaded and avoid dependency issues.

The only downside to this is that you must handle plugin dependencies yourself (ie, load xep_0030 before xep_0050) for now since things will blow up if the post_init method tries to interact with an unloaded plugin. But that's really not much different than the current situation.

**Comment by fritzy** [comment]
Thanks. I reviewed and implemented your patches.  Thanks for all of the awesome work!
