### ISSUE TITLE
Sleekxmpp no longer works with python2.6 due to unicode args

### ISSUE THREAD

**Issue by mofrank** [fritzy/SleekXMPP#295]
Sleek no longer supports python2.6 ,   Unfortunately we are using it in an embedded environment where it is not practical to upgrade to 2.7.  

The core issue is that python2.6 does not support passing unicode args to C extensions.   Several of the modules import unicode_literals. e.g. "from **future** import , unicode_literals"

Several places in the code fail, ( see sample below. ),    For our own use I have some ugly hacks that fixes these the calls that I can find but the fix is a bit ugly and would not work universally.   

I would be happy to help fix this so that I do not have to patch each new version but I am not sure what is the best approach.

---

```
    ssl_args = {
        'certfile': self.certfile,
        'keyfile': self.keyfile,
        'ca_certs': self.ca_certs,
        'cert_reqs': cert_policy,
        'do_handshake_on_connect': False,
    }

    if sys.version_info >= (2, 7):
        ssl_args['ciphers'] = self.ciphers

    ssl_socket = ssl.wrap_socket(self.socket, **ssl_args);
```

**Comment by legastero** [comment]
I vaguely remember dealing with this before. Is this an issue for specific versions of Py2.6? 

My local installation isn't having trouble with these cases, but that's 2.6.8.

**Comment by legastero** [comment]
Ah, according to http://stackoverflow.com/questions/809796/any-gotchas-using-unicode-literals-in-python-2-6 this issue would apply to anything <2.6.5

**Comment by mofrank** [comment]
It is possible,   We are stuck at 2.6.4 for the foreseeable future.

Python 2.6.4 (r264:75706, Apr 13 2012, 17:25:19) 
[GCC 4.3.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.


On Sat, 2014-06-07 at 20:09 -0700, Lance Stout wrote:

> I vaguely remember dealing with this before. Is this an issue specific
> versions of Py2.6? 
> 
> My local installation isn't having trouble with these cases, but
> that's 2.6.8.
> 
> —
> Reply to this email directly or view it on GitHub.

##

**Comment by legastero** [comment]
Fixed in v1.3.0. If you find any other spots with this issue, let me know.

**Comment by mathieui** [comment]
Actually, this fixing that issue  (60b050b82a474e2fcecd17bfe04469f0e2db3c30) breaks sleekxmpp for python 3 (at least 3.4); exact same issue, but the other way around, as “keywords must be strings”.

``` python
2014-06-09 14:09:12,820 ERROR:basexmpp:wrap_socket() keywords must be strings
Traceback (most recent call last):
  File "/home/mathieui/dev/poezio/src/sleekxmpp/xmlstream/xmlstream.py", line 1481, in _process
    if not self.__read_xml():
  File "/home/mathieui/dev/poezio/src/sleekxmpp/xmlstream/xmlstream.py", line 1553, in __read_xml
    self.__spawn_event(xml)
  File "/home/mathieui/dev/poezio/src/sleekxmpp/xmlstream/xmlstream.py", line 1621, in __spawn_event
    handler.prerun(stanza_copy)
  File "/home/mathieui/dev/poezio/src/sleekxmpp/xmlstream/handler/callback.py", line 64, in prerun
    self.run(payload, True)
  File "/home/mathieui/dev/poezio/src/sleekxmpp/xmlstream/handler/callback.py", line 76, in run
    self._pointer(payload)
  File "/home/mathieui/dev/poezio/src/sleekxmpp/features/feature_starttls/starttls.py", line 64, in _handle_starttls_proceed
    if self.xmpp.start_tls():
  File "/home/mathieui/dev/poezio/src/sleekxmpp/xmlstream/xmlstream.py", line 856, in start_tls
    ssl_socket = ssl.wrap_socket(self.socket, **ssl_args);
```

This probably requires an ugly version check to instantiate the dict.

**Comment by legastero** [comment]
Gah!

Fixed again. I added a `safedict()` function to `sleekxmpp.util` that will convert a dictionary to the appropriate form based on python version, so that should make things cleaner if any other spots require this.
