### ISSUE TITLE
eventRunner thread stops responding after stream reconnect

### ISSUE THREAD

**Issue by echamberlain** [fritzy/SleekXMPP#30]
I have a component that responds to  Service Discovery requests.  After a while, the stream disconnects and the server component reconnects.  The stream is re-established, but as you can see in the logs below, the component stops responding.

I think the problem is with the eventRunner thread.  It quits after the stream disconnects and is not restarted.

Is there a way to restart the eventRunner thread?

Correct behavior:

DEBUG    RECV: <ns0:iq from="component.example.com" id="825-32823" to="msm.example.com" type="get" xmlns:ns0="jabber:component:accept"><ns1:query xmlns:ns1="http://jabber.org/protocol/disco#info" />/ns0:iq
DEBUG    Info request from component.example.com
DEBUG    SEND: <iq xmlns="jabber:client" from="msm.example.com" type="result" id="825-32823" to="component.example.com"><query xmlns="http://jabber.org/protocol/disco#info"><identity category="client" type="pc" name="SleekXMPP" /><identity category="automatition" type="rpc" /><identity category="automatition" type="rpc" /><feature var="http://jabber.org/protocol/disco#info" /><feature var="http://jabber.org/protocol/disco#items" /><feature var="jabber:iq:rpc" /><feature var="http://www.xmpp.org/extensions/xep-0199.html#ns" /><feature var="jabber:iq:rpc" /><feature var="http://www.xmpp.org/extensions/xep-0199.html#ns" /></query></iq>

Behavior after the stream reconnects:

DEBUG    RECV: <ns0:iq from="component.example.com" id="72-32824" to="msm.example.com" type="get" xmlns:ns0="jabber:component:accept"><ns1:query xmlns:ns1="http://jabber.org/protocol/disco#info" />/ns0:iq

Full logs below:

(msm)[root@host xmpp]# python service.py --debug
DEBUG    Loaded Plugin (XEP-0030) Service Discovery
DEBUG    Loaded Plugin (XEP-0009) Jabber-RPC
DEBUG    Loaded Plugin (XEP-0199) XMPP Ping
DEBUG    Connecting to xmpp.example.com:5275
DEBUG    Loading event runner
DEBUG    SEND: <stream:stream xmlns='jabber:component:accept' xmlns:stream='http://etherx.jabber.org/streams' to='msm.example.com'>
DEBUG    SEND: <handshake xmlns="jabber:component:accept">d0dae26cfb9af754a2152b8ded53ee556f3905c6</handshake>
DEBUG    RECV: <ns0:handshake xmlns:ns0="jabber:component:accept" />
DEBUG    XMPP connected
DEBUG    RECV: <ns0:iq from="component.example.com" id="825-32823" to="msm.example.com" type="get" xmlns:ns0="jabber:component:accept"><ns1:query xmlns:ns1="http://jabber.org/protocol/disco#info" />/ns0:iq
DEBUG    Info request from component.example.com
DEBUG    SEND: <iq xmlns="jabber:client" from="msm.example.com" type="result" id="825-32823" to="component.example.com"><query xmlns="http://jabber.org/protocol/disco#info"><identity category="client" type="pc" name="SleekXMPP" /><identity category="automatition" type="rpc" /><identity category="automatition" type="rpc" /><feature var="http://jabber.org/protocol/disco#info" /><feature var="http://jabber.org/protocol/disco#items" /><feature var="jabber:iq:rpc" /><feature var="http://www.xmpp.org/extensions/xep-0199.html#ns" /><feature var="jabber:iq:rpc" /><feature var="http://www.xmpp.org/extensions/xep-0199.html#ns" /></query></iq>
DEBUG    SEND: /stream:stream
DEBUG    Connecting to xmpp.example.com:5275
Traceback (most recent call last):
 File "/home/django/projects/msm/lib/python2.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 171, in _process
   while self.run and self.__readXML():
 File "/home/django/projects/msm/lib/python2.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 217, in __readXML
   for (event, xmlobj) in cElementTree.iterparse(self.filesocket, (b'end', b'start')):
 File "<string>", line 61, in __iter__
 File "/home/django/projects/msm/lib/python2.6/site-packages/sleekxmpp/xmlstream/filesocket.py", line 14, in read
   data = self._sock.recv(size)
AttributeError: 'NoneType' object has no attribute 'recv'
DEBUG    SEND: <stream:stream xmlns='jabber:component:accept' xmlns:stream='http://etherx.jabber.org/streams' to='msm.example.com'>
WARNING  Failed to send <stream:stream xmlns='jabber:component:accept' xmlns:stream='http://etherx.jabber.org/streams' to='msm.example.com'>
ERROR    Disconnected. Socket Error.
Traceback (most recent call last):
 File "/home/django/projects/msm/lib/python2.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 245, in _sendThread
   self.socket.send(data.encode('utf-8'))
 File "/usr/local/lib/python2.6/socket.py", line 165, in _dummy
   raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
DEBUG    SEND: /stream:stream
WARNING  Failed to send /stream:stream
ERROR    Disconnected. Socket Error.
Traceback (most recent call last):
 File "/home/django/projects/msm/lib/python2.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 245, in _sendThread
   self.socket.send(data.encode('utf-8'))
 File "/usr/local/lib/python2.6/socket.py", line 165, in _dummy
   raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
DEBUG    Quitting eventRunner thread
DEBUG    Connecting to xmpp.example.com:5275
DEBUG    SEND: <stream:stream xmlns='jabber:component:accept' xmlns:stream='http://etherx.jabber.org/streams' to='msm.example.com'>
DEBUG    SEND: <handshake xmlns="jabber:component:accept">61c82993e70ab4dd263ee962637ab8d5168732af</handshake>
DEBUG    RECV: <ns0:handshake xmlns:ns0="jabber:component:accept" />
DEBUG    RECV: <ns0:iq from="component.example.com" id="72-32824" to="msm.example.com" type="get" xmlns:ns0="jabber:component:accept"><ns1:query xmlns:ns1="http://jabber.org/protocol/disco#info" />/ns0:iq
DEBUG    SEND: /stream:stream

**Comment by echamberlain** [comment]
Posted a patch to the mailing list.

**Comment by fritzy** [comment]
this should be fixed in the beta, but I will do more testing on components this week.

**Comment by legastero** [comment]
This is fixed by now with Beta6.
