### ISSUE TITLE
SleekXMPP Installation issues

### ISSUE THREAD

**Issue by Aminiok** [fritzy/SleekXMPP#312]
Hello,

As a new SleekXMPP user, I installed the SleekXMPP from the source : https://github.com/fritzy/SleekXMPP/archive/develop.zip
The I ran the test suite by: # python testall.py
And I received a typical type error message : TypeError: _connect() got an unexpected keyword argument 'args'
Would you, please, help me to resolve the problem?

Best regards,
Amin

**Comment by bear** [comment]
I just ran "python testall.py" for Python v2.6, v2.7 and v3.4 and did not see this error so I'm thinking it was fixed recently.
