### ISSUE TITLE
why so bad wiki, document and Community around this lib.

### ISSUE THREAD

**Issue by hackrole** [fritzy/SleekXMPP#325]
I have read some of the lib source code. I have to say the sleekxmpp is a good lib.

but the wiki and document is so bad. even good pythoner is hard to start for a real application.

and the github issues or the google groups can never got a answer.

can anyone tell why a good lib has such situation?

**Comment by BaseMax** [comment]
Check sleekxmpp.com

**Comment by kxepal** [comment]
@hackrole you can always help the project to have good wiki, better documentation, simple and clean tutorials and help others on GH / GG - every bit of help is always welcome! (:

But in overall, XMPP (as well as other IMs) now isn't so popular as it was several years ago and this causes a bit lack of interest.

**Comment by hackrole** [comment]
@kxepal, I will do it  when  I have time.
