### ISSUE TITLE
sdist tarball fails to install - missing file error

### ISSUE THREAD

**Issue by bear** [fritzy/SleekXMPP#34]
"python setup.py sdist" created tarball sleekxmpp-0.2.3.1.tar.gz and that tarball, when run with python2.6 setup.py install generates the following output:

(testsleek)moz:sleekxmpp-0.2.3.1 bear$ python setup.py install
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/sleekxmpp
copying sleekxmpp/**init**.py -> build/lib/sleekxmpp
copying sleekxmpp/basexmpp.py -> build/lib/sleekxmpp
creating build/lib/sleekxmpp/plugins
copying sleekxmpp/plugins/**init**.py -> build/lib/sleekxmpp/plugins
copying sleekxmpp/plugins/base.py -> build/lib/sleekxmpp/plugins
copying sleekxmpp/plugins/gmail_notify.py -> build/lib/sleekxmpp/plugins
copying sleekxmpp/plugins/xep_0004.py -> build/lib/sleekxmpp/plugins
copying sleekxmpp/plugins/xep_0009.py -> build/lib/sleekxmpp/plugins
copying sleekxmpp/plugins/xep_0030.py -> build/lib/sleekxmpp/plugins
copying sleekxmpp/plugins/xep_0045.py -> build/lib/sleekxmpp/plugins
copying sleekxmpp/plugins/xep_0050.py -> build/lib/sleekxmpp/plugins
copying sleekxmpp/plugins/xep_0060.py -> build/lib/sleekxmpp/plugins
copying sleekxmpp/plugins/xep_0078.py -> build/lib/sleekxmpp/plugins
copying sleekxmpp/plugins/xep_0086.py -> build/lib/sleekxmpp/plugins
copying sleekxmpp/plugins/xep_0092.py -> build/lib/sleekxmpp/plugins
copying sleekxmpp/plugins/xep_0199.py -> build/lib/sleekxmpp/plugins
creating build/lib/sleekxmpp/stanza
copying sleekxmpp/stanza/**init**.py -> build/lib/sleekxmpp/stanza
copying sleekxmpp/stanza/iq.py -> build/lib/sleekxmpp/stanza
copying sleekxmpp/stanza/message.py -> build/lib/sleekxmpp/stanza
copying sleekxmpp/stanza/presence.py -> build/lib/sleekxmpp/stanza
creating build/lib/sleekxmpp/xmlstream
copying sleekxmpp/xmlstream/**init**.py -> build/lib/sleekxmpp/xmlstream
copying sleekxmpp/xmlstream/stanzabase.py -> build/lib/sleekxmpp/xmlstream
copying sleekxmpp/xmlstream/statemachine.py -> build/lib/sleekxmpp/xmlstream
copying sleekxmpp/xmlstream/test.py -> build/lib/sleekxmpp/xmlstream
copying sleekxmpp/xmlstream/testclient.py -> build/lib/sleekxmpp/xmlstream
copying sleekxmpp/xmlstream/xmlstream.py -> build/lib/sleekxmpp/xmlstream
creating build/lib/sleekxmpp/xmlstream/matcher
copying sleekxmpp/xmlstream/matcher/**init**.py -> build/lib/sleekxmpp/xmlstream/matcher
copying sleekxmpp/xmlstream/matcher/base.py -> build/lib/sleekxmpp/xmlstream/matcher
copying sleekxmpp/xmlstream/matcher/many.py -> build/lib/sleekxmpp/xmlstream/matcher
copying sleekxmpp/xmlstream/matcher/xmlmask.py -> build/lib/sleekxmpp/xmlstream/matcher
copying sleekxmpp/xmlstream/matcher/xpath.py -> build/lib/sleekxmpp/xmlstream/matcher
creating build/lib/sleekxmpp/xmlstream/handler
copying sleekxmpp/xmlstream/handler/**init**.py -> build/lib/sleekxmpp/xmlstream/handler
copying sleekxmpp/xmlstream/handler/base.py -> build/lib/sleekxmpp/xmlstream/handler
copying sleekxmpp/xmlstream/handler/callback.py -> build/lib/sleekxmpp/xmlstream/handler
copying sleekxmpp/xmlstream/handler/waiter.py -> build/lib/sleekxmpp/xmlstream/handler
copying sleekxmpp/xmlstream/handler/xmlcallback.py -> build/lib/sleekxmpp/xmlstream/handler
copying sleekxmpp/xmlstream/handler/xmlwaiter.py -> build/lib/sleekxmpp/xmlstream/handler
error: package directory 'sleekxmpp/xmlstream/tostring26' does not exist

**Comment by fritzy** [comment]
This has to do with the way we're using the MANIFEST file.

5 points for hackfest

**Comment by fritzy** [comment]
1 point cause I'm dumb.

**Comment by fritzy** [comment]
test sdist to make sure this works before closing
