### ISSUE TITLE
Error stanza hardcoded to use jabber:client namespace

### ISSUE THREAD

**Issue by echamberlain** [fritzy/SleekXMPP#35]
The Error stanza is hardcoded to use the jabber:client namespace.  In the case of components, this namespace is incorrect.

The Error stanza should derive the namespace from the stream namespace.

**Comment by fritzy** [comment]
I believe this is fixed, but I'll give 2 hackfest point for confirming.

**Comment by fritzy** [comment]
This is not fixed, but this is also not inappropriate.  If you're in the component namespace, having a jabber:client namespace error is still valid.
