### ISSUE TITLE
503 Service unavailable witj Custom Stanza and Ejabberd

### ISSUE THREAD

**Issue by vsidou** [fritzy/SleekXMPP#355]
Hi,

I wonder if someone could point me out here please.
I've installed a fresh version (latest 15.03) and created a few users.

I cloned the latest version of sleekxmpp.
I wanted to test the Custom stanza example : 
https://github.com/fritzy/SleekXMPP/tree/develop/examples/custom_stanzas

I started the custom_stanza_provider.py with an account.
I fired the custom_stanza_user.py with another account and pointing to the previous jid (provider).
Connection and authentication is fine. 
But when the parts where it tries to send the custom "Action" IQ i get a 503 service unavailable from Ejabberd. 
Did i miss something ?

Thank you

**Comment by vsidou** [comment]
Hi Again,

my bad i was using the username@domain for the target.
Instead i should input the full JID including provided id.

I'll close the issue.

Regards

**Comment by prafulbagai** [comment]
What exactly is the `id` here? Where did you fetch it from?
