### ISSUE TITLE
Error: Could not register account error code=403

### ISSUE THREAD

**Issue by pythonshiva** [fritzy/SleekXMPP#374]
When i am trying to register account with example 'register_account.py' i am getting the following error.

DEBUG Loaded Plugin: RFC 6120: Stream Feature: STARTTLS
DEBUG Loaded Plugin: RFC 6120: Stream Feature: Resource Binding
DEBUG Loaded Plugin: RFC 3920: Stream Feature: Start Session
DEBUG Loaded Plugin: RFC 6121: Stream Feature: Roster Versioning
DEBUG Loaded Plugin: RFC 6121: Stream Feature: Subscription Pre-Approval
DEBUG Loaded Plugin: RFC 6120: Stream Feature: SASL
DEBUG Loaded Plugin: XEP-0030: Service Discovery
DEBUG Loaded Plugin: XEP-0004: Data Forms
DEBUG Loaded Plugin: XEP-0066: Out of Band Data
DEBUG Loaded Plugin: XEP-0077: In-Band Registration
WARNING DNS: dnspython not found. Can not use SRV lookup.
DEBUG DNS: Querying jitsi.iton.net for AAAA records.
DEBUG DNS: Error retreiving AAAA address info for jitsi.iton.net.
DEBUG DNS: Querying jitsi.iton.net for A records.
DEBUG Connecting to 1xx.xxx.x.xx:5222
DEBUG Event triggered: connected
DEBUG ==== TRANSITION disconnected -> connected
DEBUG Starting HANDLER THREAD
DEBUG Loading event runner
DEBUG SEND (IMMED): 
DEBUG RECV: xml:lang="en">
DEBUG RECV: isms xmlns="urn:ietf:params:xml:ns:xmpp-sasl">PLAIN nism>DIGEST-MD5SCRAM-SHA-1 ns="http://jabber.org/protocol/caps" node="http://www.process-one.net/en/ejabber
d/" ver="DksZ6FHJJWRiYER6w6zl0DGK7+Y=" hash="sha-1" />/stream:features
DEBUG SEND (IMMED): 
DEBUG RECV: Choose a user
name and password to register with this server rd />
DEBUG Event triggered: register
DEBUG SEND (IMMED): mulagalamulagala@
123
DEBUG RECV: mulagala</username

mulagala@123 mlns="urn:ietf:params:xml:ns:xmpp-stanzas" />
ERROR Could not register account:
DEBUG Event triggered: session_end
DEBUG SEND (IMMED): /stream:stream
INFO Waiting for /stream:stream from server
DEBUG End of stream recieved
DEBUG Waiting for 3 threads to exit.
DEBUG Threading deadlock prevention!
DEBUG Marked event_thread_0 thread as ended due to disconnect() call. 2 threa
ds remain.
DEBUG Stopped send thread. 1 threads remain.
DEBUG Quitting Scheduler thread
DEBUG Stopped scheduler thread. 0 threads remain.
DEBUG Event triggered: disconnected
DEBUG ==== TRANSITION connected -> disconnected
DEBUG Channel binding not supported.
DEBUG Use Python 3.3+ for channel binding and SCRAM-SHA-1-PLUS support
DEBUG SEND (IMMED): "SCRAM-SHA-1">biwsbj1tdWxhZ2FsYSxyPTAxNTQwNzcyODU1MDY=
DEBUG Finished exiting event runner thread after early termination from disco
nnect() call. 0 threads remain.
DEBUG State was not ready
Done
What should i do..?

**Comment by jdowner** [comment]
Just a thought, are entering the full jid? mulagala@jitsi.iton.net?

**Comment by pythonshiva** [comment]
Yes, Because it should know to which domain it connect..?
