### ISSUE TITLE
a threading issue in jid.py

### ISSUE THREAD

**Issue by coffeeowl** [fritzy/SleekXMPP#378]
I am trying to solve a mysterious bug I have in my app, so far it points to jid.py and looks like a multithreading issue:

```
 jid = JID(n['node'])
 File "/usr/local/lib/python2.7/dist-packages/sleekxmpp/jid.py", line 478, in __init__
   _cache(key, self._jid, locked)
   File "/usr/local/lib/python2.7/dist-packages/sleekxmpp/jid.py", line 80, in _cache
       for key, item in JID_CACHE.items():
       File "/usr/lib/python2.7/collections.py", line 113, in items
            return [(key, self[key]) for key in self]
            KeyError: 'myid@mydomain.com/0'
```

In my code I am just trying to create a new JID instance and end up with an exception, of course not easily reproducible. SleekXMPP runs in its own thread.

**Comment by bear** [comment]
You already have an instance of Sleek running for a JID and are trying to get that instance to now handle another JID?

If so that won't work - Sleek is multi-threaded yes but assumes that each instance is only for a single JID.

**Comment by coffeeowl** [comment]
I don't think so, I am just constructing a JID class instance because I need to extract some parts from it.

**Comment by bear** [comment]
ohh, I may have misread it then - apologies.

I'll swing back to this issue then

**Comment by mcella** [comment]
Today we've got the same traceback, it's indeed a multithreading issue in `jid.py`.

Basically the `jid._cache` function should acquire the `JID_CACHE_LOCK` **before** adding an entry to the `JID_CACHE` OrderedDict.

`OrderedDict.__setitem__` is not an atomic call, calling it from multiple threads can lead to a corrupted structure, you can just run this little script: 

```
import threading
import uuid
from collections import OrderedDict

od = OrderedDict()

def run():
    for x in range(5000):
        od[uuid.uuid4()] = None
    od.items()

for i in range(100):
    t = threading.Thread(target=run)
    t.start()
```

to reproduce the issue:

```
Exception in thread Thread-25:
Traceback (most recent call last):
  ...
  File "/opt/python/lib/python2.7/collections.py", line 113, in items
    return [(key, self[key]) for key in self]
KeyError: UUID('46dfe80d-8c2a-4841-9509-c6b5310d5806')
```

I'm preparing a pull request that fixes this problem.

**Comment by mcella** [comment]
See pull request #387

**Comment by bear** [comment]
Thanks for tracking this down and the pull request!
