### ISSUE TITLE
Unable to add new roster?

### ISSUE THREAD

**Issue by ravipadu** [fritzy/SleekXMPP#379]
I am trying to add new roster, when i am adding a new roster with the below function

`self.update_roster('ss@iton-satya.local', name='ss',subscription='remove',timeout=10, groups=['Python'])`

then roster in my account showing as `unauthorized` 
and at the receiver end i am not getting the roster request.

**Comment by elya5** [comment]
If your problem is that you want to remove an entry from the roster but the jid is not notified, you need to use `BaseXMPP.sendPresence()` (see [docs](http://sleekxmpp.com/api/basexmpp.html#sleekxmpp.basexmpp.BaseXMPP.sendPresence)) with `ptype='unsubscribe'`.

**Comment by bear** [comment]
marking as a closed question
