### ISSUE TITLE
MUC plugin still thinks it's in the room after it's been kicked out

### ISSUE THREAD

**Issue by antonv6** [fritzy/SleekXMPP#411]
XEP_0045 plugin does this in `handle_groupchat_invite()`:

``` python
if inv['from'] not in self.rooms.keys():
    self.xmpp.event("groupchat_invite", inv)
```

And this in `leaveMUC()`:

``` python
del self.rooms[room]
```

So far so good - if the bot leaves (voluntarily) a room, then it can be invited to it again (i.e. it will handle the invite).

Unfortunately, if the bot is kicked, `self.rooms` is not updated and so the bot will no longer handle invites.

**Comment by bear** [comment]
fixed by PR https://github.com/fritzy/SleekXMPP/pull/408
