### ISSUE TITLE
Remove two-digit-year variants from certificate validity date decoding 

### ISSUE THREAD

**Issue by bear** [fritzy/SleekXMPP#461]
Issue reported via Debian - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864257

Patch was given so i'm applying it and will spin up a point release.

**Comment by bear** [comment]
fixed in v1.3.3 and merged into current develop branch

**Comment by bdauvergne** [comment]
This fix is wrong, it broke support for UTCTime, I published a pull request with a fix, but it would be probably better to revert this commit and move the conversion to string inside the if/else blocks (the original problem was that premature conversion to string broke the isinstance() test).

**Comment by mickeprag** [comment]
I agree with bdauvergne that the fix is not working. This break since my certificate do report the year using only two digits...

**Comment by skoczen** [comment]
@bear Another +1 to this being an problematic fix - 1.3.3 is currently broken on all hipchat servers due to invalid cert, 1.3.2 works fine.

**Comment by starstuck** [comment]
I think, that library should support both variants. I have proposed a pull request #472, that uses pyasn1 library methods for dates conversion, rather than parsing String representation. I think this will help with your problem as well, but I have not tested it with hipchat servers.

**Comment by mfin** [comment]
I agree, library should support both formats.

**Comment by jogzug7** [comment]
Please reopen this bug. IMHO, the "fix" was wrong. See also https://bugs.debian.org/864257 which is reopened.

**Comment by Neustradamus** [comment]
There is a real fix?
- 1.3.3 is broken
- 1.3.2 is ok
