### ISSUE TITLE
session_start not working

### ISSUE THREAD

**Issue by salmanasiddiqui** [fritzy/SleekXMPP#463]
```
import sleekxmpp


class SendMsgBot(sleekxmpp.ClientXMPP):
	def __init__(self, jid, password, recipient, message):
		sleekxmpp.ClientXMPP.__init__(self, jid, password)
		self.recipient = recipient
		self.msg = message
		self.add_event_handler("session_start", self.start)
		self.add_event_handler("message", self.msg)

	def start(self, event):
		raise('it wont fail it wont end')
		self.send_presence()
		self.get_roster()

		self.send_message(mto=self.recipient,
				mbody=self.msg,
				mtype='chat')

	def message(self, msg):
		if msg['type'] in ('chat', 'normal'):
			msg.reply("Thanks for sending\n%(body)s" % msg).send()


if __name__ == '__main__':
	xmpp = SendMsgBot(
			'some jid',
			'password',
			'someother jid',
			'blahblah'
	)
	xmpp.register_plugin('xep_0030')  # Service Discovery
	xmpp.register_plugin('xep_0004')  # Data Forms
	xmpp.register_plugin('xep_0060')  # PubSub
	if xmpp.connect():
		xmpp.process(block=True)
		print("Done")
	else:
		print("Unable to connect.")

```

the above code should raise an exception as soon as the `self.start` is called but that wont happen. This code is similar to one of the examples in the repo.
Without that raise it should complete the steps and disconnect, but that never happens aswell.

**Comment by 5aurabhpathak** [comment]
I'm facing this issue as well. Any updates?

**Comment by LisaOneLogic** [comment]
I have the same issue. @5aurabhpathak did you find a solution?

**Comment by Neustradamus** [comment]
@salmanasiddiqui @5aurabhpathak @LisaOneLogic: Have you tested with "master"?
- https://github.com/fritzy/SleekXMPP/commits/develop

Always same?
Have you a patch?
Can you create a PR?

**Comment by salmanasiddiqui** [comment]
- back then it was always happening, the `start` function was not being called.
- No I ditched this library and went with other xmpp client
- 😕 

feel free to close this issue.. if it exists in the latest version, then someone will create another issue and will be able to provide more info

**Comment by Neustradamus** [comment]
@salmanasiddiqui What do you use now? :/

**Comment by salmanasiddiqui** [comment]
I was trying to use this to write some tests, ended up doing some manual testing using gui based xmpp clients, and then used jmeter for basic stress testing
