### ISSUE TITLE
Expanded plugin registration

### ISSUE THREAD

**Issue by macdiesel** [fritzy/SleekXMPP#47]
Currently if you want to write a plugin for sleek it must reside in the the sleekxmpp/plugins package.  We have a requirement that we must be able to load a sleekxmpp plugin regardless of package.  I have a simple patch for this that preserves existing functionality while adding the option of specifying the full package of a plugin to allow loading from any package.

The patch can be found here:
http://github.com/macdiesel/SleekXMPP/blob/4e2df7d48a8ec4ef52473c2cfe6b5246212520a9/sleekxmpp/basexmpp.py#L90-100

**Comment by fritzy** [comment]
I like this.

**Comment by legastero** [comment]
This currently works in the develop branch, using module= instead of pluginModule=.

The module reference may be either an actual module containing the plugin or a string reference.
