### ISSUE TITLE
Multiple license issue

### ISSUE THREAD

**Issue by macdiesel** [fritzy/SleekXMPP#48]
I believe this project is now on the MIT license (yay) but there are still references to the GNU GPL2+ in some of the headers of the files.  (xep_0199 being one example).

First I wanted to confirm that the project is now on the MIT license.  If so I can go back and add ensure the correct header information is on all files so the licensing for the project is correct.

**Comment by fritzy** [comment]
Yes, this is MIT. I will clean this up today.

**Comment by fritzy** [comment]
Or you can.  I'll be reviewing your forks today as well (if all goes well).

**Comment by legastero** [comment]
Done, in experimental branch now.
