### ISSUE TITLE
groupcat_invite event patch for xep_0045

### ISSUE THREAD

**Issue by damium** [fritzy/SleekXMPP#52]
The following patch adds a new event for received xep_0045 invite messages: groupchat_invite

<pre><code>
--- a/sleekxmpp/plugins/xep_0045.py
+++ b/sleekxmpp/plugins/xep_0045.py
@@ -128,6 +128,7 @@ class xep_0045(base.base_plugin):
                self.xmpp.stanzaPlugin(Presence, MUCPresence)
                self.xmpp.registerHandler(Callback('MUCPresence', MatchXMLMask("<presence xmlns='%s' />" % self.xmpp.default_ns), self.handle_groupchat_presence))
                self.xmpp.registerHandler(Callback('MUCMessage', MatchXMLMask("<message xmlns='%s' type='groupchat'><body/></message>" % self.xmpp.default_ns), self.handle_groupchat_message))
+               self.xmpp.registerHandler(Callback('MUCInvite', MatchXMLMask("<message xmlns='%s'><x xmlns='http://jabber.org/protocol/muc#user'><invite /></x></message>" % self.xmpp.default_ns), self.handle_groupchat_invite))

        def handle_groupchat_presence(self, pr):
                """ Handle a presence in a muc.
@@ -141,6 +142,13 @@ class xep_0045(base.base_plugin):
                        self.rooms[entry['room']][entry['nick']] = entry
                logging.debug("MUC presence from %s/%s : %s" % (entry['room'],entry['nick'], entry))
                self.xmpp.event("groupchat_presence", pr)
+
+       def handle_groupchat_invite(self, inv):
+               """ Handle an invite into a muc. """
+               logging.debug("MUC invite to %s from %s: %s" % (inv['from'], inv["from"], inv))
+               if inv['from'] in self.rooms.keys():
+                       return
+               self.xmpp.event("groupchat_invite", inv)

        def handle_groupchat_message(self, msg):
                """ Handle a message event in a muc.
</code></pre>

**Comment by talfonsin** [comment]
This patch didn't work. In the link below you will find a modified patch working on current trunk. Please test and consider applying it to trunk.

Thanks in advance

Edited: 
I apoligize for the previous patch, it was wrong. 
The link below is a patch which works with trunk version

http://pastebin.com/u0238Ki6

**Comment by legastero** [comment]
Thanks for the patch!

I've added it with some slight tweaking to the develop branch.
