### ISSUE TITLE
[Patch] Anonymous Authentication

### ISSUE THREAD

**Issue by louiz** [fritzy/SleekXMPP#55]
Here is a little patch enabling to Anonymously authenticate.
This method is described in the XEP 0175: http://xmpp.org/extensions/xep-0175.html (and RFC 4505 linked in the XEP page)

http://louiz.org/~louiz/patches/sleekxmpp/anon_authentication.patch

To use it, simply do this:

client = sleekxmpp.ClientXMPP(None, None, ssl=True, resource='OptionalResource')
client.connect(('anon.server.net', 5222))

(if no resource is set, the server will attribute a random one)

**Comment by legastero** [comment]
Added in develop branch.
