### ISSUE TITLE
sleekxmpp not in PyPi

### ISSUE THREAD

**Issue by pferreir** [fritzy/SleekXMPP#61]
Hello,

I'd like to use `sleekxmpp` as a dependency of my application. We are currently using `setuptools`, which automatically fetches all the required packages.
Would it be possible to have a PyPi entry for `sleekxmpp`? It would be much easier to install it this way, as our users wouldn't have to download it manually.

Thanks in advance!

Pedro
(Indico Project - http://indico-software.org)

**Comment by legastero** [comment]
Hi Pedro,

Our plan so far is to put Sleek on PyPI once we reach the 1.0 release, after the API changes have settled.

**Comment by fritzy** [comment]
We're pretty close with this, as we're just testing the last major hurdle on gettting 1.0 beta 1 out the door.

**Comment by fritzy** [comment]
To clarify, I'm backing up what legastero said... I'm just saying that 1.0 is soon. Just release beta 1! w00t

**Comment by pferreir** [comment]
Thanks! I'll wait for v1.0 then :)

**Comment by ninowalker** [comment]
It would be incredibly nice to have this.  The last commit was mid-november, so maybe you call it good enough, and put to pypi as 1.0b4? 

There are plenty of beta packages in the cheeseshop :)

**Comment by fritzy** [comment]
The latest merge to master was in mid-november. There are commits most every day.

**Comment by ninowalker** [comment]
Yep, as we later discovered.  After investigation we decided to go back to PyXMPP as things like MD5 auth actually work in that module.
