### ISSUE TITLE
echo_client.py doesn't run

### ISSUE THREAD

**Issue by andrzej-bieniek** [fritzy/SleekXMPP#63]
<pre>
$ pip freeze
distribute==0.6.10
-e git+http://github.com/fritzy/SleekXMPP.git@5bdcd9ef9d74d7921f5579086e6c6d94c0ac7deb#egg=sleekxmpp-1.0-Beta2
wsgiref==0.1.2
</pre>

Almost all plugins are failing, e.g.:

<pre>
$ python src/package/examples/echo_client.py -j <user> -p <pass>
INFO     Negotiating TLS
INFO     Node set to: None
ERROR    Error processing event handler: <bound method xep_0030.handle_disco_info of <sleekxmpp.plugins.xep_0030.xep_0030 object at 0x8da5f6c>>
Traceback (most recent call last):
  File "/home/andi/mysource/im/framework/jbve/src/package/sleekxmpp/xmlstream/xmlstream.py", line 851, in _event_runner
    func(*args)
  File "/home/andi/mysource/im/framework/jbve/src/package/sleekxmpp/plugins/xep_0030.py", line 244, in handle_disco_info
    handlers = self.xmpp.event_handlers['disco_info_request']
AttributeError: 'EchoBot' object has no attribute 'event_handlers'
ERROR    Error processing event handler: <bound method xep_0030.handle_disco_info of <sleekxmpp.plugins.xep_0030.xep_0030 object at 0x8da5f6c>>
Traceback (most recent call last):
  File "/home/andi/mysource/im/framework/jbve/src/package/sleekxmpp/xmlstream/xmlstream.py", line 851, in _event_runner
    func(*args)
  File "/home/andi/mysource/im/framework/jbve/src/package/sleekxmpp/plugins/xep_0030.py", line 244, in handle_disco_info
    handlers = self.xmpp.event_handlers['disco_info_request']
AttributeError: 'EchoBot' object has no attribute 'event_handlers'
</pre>

**Comment by andrzej-bieniek** [comment]
This patches fixes it, but I guess it is not a solution?

<pre>
diff --git a/sleekxmpp/plugins/xep_0030.py b/sleekxmpp/plugins/xep_0030.py
index a9d8d6a..e8e903d 100644
--- a/sleekxmpp/plugins/xep_0030.py
+++ b/sleekxmpp/plugins/xep_0030.py
@@ -241,7 +241,8 @@ class xep_0030(base.base_plugin):
                A default handler for disco#info requests. If another
                handler is registered, this one will defer and not run.
                """
-               handlers = self.xmpp.event_handlers['disco_info_request']
+               handlers = []
+#        handlers = self.xmpp.event_handlers['disco_info_request']
                if not forwarded and len(handlers) > 1:
                        return
</pre>

**Comment by legastero** [comment]
Hi andyhelp, I just pushed a fix to the develop branch.

The XEP-0030 plugin currently tries to find if any event handlers are registered for handling disco requests to determine if a default handler should be used. Since event handlers are stored in a different location now, I added a new method to return the number of handlers for an event.

**Comment by andrzej-bieniek** [comment]
Thanks lagastero!

I have checked out develop branch. It works :)
