### ISSUE TITLE
Ping namespace (XEP-0199 plugin)

### ISSUE THREAD

**Issue by thom-nic** [fritzy/SleekXMPP#64]
The current xep_0199 plugin uses an xmlns of 'http://www.xmpp.org/extensions/xep-0199.html#ns' -- Is this right?  The XEP says the namespace should be **urn:xmpp:ping**.  And certainly the plugin doesn't respond to any entity which uses the **urn:xmpp:ping** namespace.  So the plugin should at least support both namespaces.

I'm wondering where a namespace of http://....xmpp.org/...xep-0199.html#ns is valid _at all_ I can't find any reference to any other software using that namespace in an XMPP ping message.  Maybe it should just be changed?

**Comment by legastero** [comment]
The http://www.xmpp.org/extensions/xep-0199.html#ns namepsace was introduced in version 0.3 of XEP-0199 as a temporary namespace until the XEP was promoted to draft status.

I think it would be safe to update that now.

**Comment by thom-nic** [comment]
Thanks for the quick response!  I will commit a fix to my branch but I am still sitting at a pre pep-8 revision so merging is likely to be a bear.

**Comment by thom-nic** [comment]
See: 1bb8bc47f6444a990e0c

**Comment by legastero** [comment]
Fixed in develop branch. The ping plugin will still need proper cleanup later though.
