### ISSUE TITLE
Event handler execution should be surrounded by a try block

### ISSUE THREAD

**Issue by thom-nic** [fritzy/SleekXMPP#65]
Currently if a 'direct' event handler raises an uncaught exception it prevents other event handlers from receiving the event.  

Queued events are properly enclosed in a 'try' block (in XMLStream._event_runner) however 'direct' events are not - see: sleekxmpp/xmlstream/xmlstream.py:532 (from Fritzy's 'master' branch)

**Comment by legastero** [comment]
Fixed in develop branch. Note that event handlers will all run in the same thread if using a direct event.

**Comment by thom-nic** [comment]
Yup!  I know it's not normally used (the queue is ideal IMO) but just wanted to make sure all conditions were covered.  Thanks!
