### ISSUE TITLE
Implement whitespace-based keepalive

### ISSUE THREAD

**Issue by thom-nic** [fritzy/SleekXMPP#66]
You can transparently implement a minimal keepalive by sending a whitespace character in between stanzas -- it's essentially ignored by XML parsers and more efficient than sending a whole ping IQ.  The Smack API implements this by default.  I've also done it in my 'hacks' branch, it's very simple.  See: tomstrummer/SleekXMPP@3c6b07353dc

**Comment by fritzy** [comment]
I'm not sure this is necessary "by default." This is typically only a problem behind NAT. A much older version of Sleek had this, and it will be re-implemented as a plugin.

**Comment by thom-nic** [comment]
Exactly!  How often are you not behind a NAT? :)  We've seen lots of firewalls shut down idle TCP connections, even with TCP keepalive turned on.

The nice thing about my implementation is (1) it only sends a single character over the socket (not a whole message) and (2) it doesn't require a separate thread to run.  Off the top of my head I can't imagine being able to do this as a plugin without violating (1 or 2).

**Comment by legastero** [comment]
Tom, I noticed that you and Brian have removed the whitespace keep alive from your branches in favor of using pings. Did you encounter any problems with the whitespace method, and, if not, is this change one we should still consider?

**Comment by thom-nic** [comment]
Personally I think a whitespace-based solution is still viable, since it requires fewer (processing and network) resources and doesn't require ping support on the server.  For that matter, it requires 0 processing resources on the server since the whitespace is ignored rather than a ping IQ being parsed and response returned.

We opted for our use case to use Ping but I think the whitespace support is a safer and simpler default keepalive mechanism.  

Users have to opt-in to using a ping keepalive by loading the ping plugin, whereas the whitespace keepalive you can enable by default and nobody needs to care or know about it :)  Smack uses this keepalive mechanism but there's no mention of it anywhere; I had to look at the source code :)

**Comment by legastero** [comment]
We've added a scheduled whitespace keepalive in RC2. It sends a space every 5min (configurable) if nothing is in the send queue.

**Comment by thom-nic** [comment]
Awesome!  Thanks.
