### ISSUE TITLE
Server certificate validation

### ISSUE THREAD

**Issue by thom-nic** [fritzy/SleekXMPP#68]
Option to validate the server's SSL certificate chain.  This prevents man-in-the-middle attacks and ensures you're actually connected to who you _think_ you're connected to :)  

This is backwards-compatible -- if xmlstream.ca_certs is unset, it does not attempt to validate the certificate.

See:
tomstrummer/SleekXMPP@8e95ae294822
tomstrummer/SleekXMPP@85d8b9270f1

**Comment by thom-nic** [comment]
Another related commit:
tomstrummer/SleekXMPP@f3cf5f6080b

**Comment by macdiesel** [comment]
Merged commit against beta-2 tag may be found here:
https://github.com/macdiesel/SleekXMPP/commit/30fc9a677a7391fd9035e96995d1ced8be19d4e3

**Comment by legastero** [comment]
Added to the develop branch.

I made some slight changes to keep line lengths shorter, and added some brief docs on self.ca_certs.

Keep up the great work you two!
