### ISSUE TITLE
digest-md5 support <patch available>

### ISSUE THREAD

**Issue by macdiesel** [fritzy/SleekXMPP#69]
I have a requirement for digest-md5 authentication.  Below is a patch that adds this support into SleekXMPP.  There are 2 commits for this:
https://github.com/macdiesel/SleekXMPP/commit/6d4f7d75678807e197a73c8fdb3764823889d0e1
http://github.com/macdiesel/SleekXMPP/commit/2cb4b21b263bc9d3e7cc12a05f5f1b0a94424752

I have tested this against Beta2

**Comment by legastero** [comment]
Beta6 integrates dwd's Suelta SASL library, which adds DIGEST-MD5, CRAM-MD5, and SCRAM-SHA-1 support.
