### ISSUE TITLE
improvement for make_iq_ methods

### ISSUE THREAD

**Issue by thom-nic** [fritzy/SleekXMPP#71]
It would be nice if all of the make_iq methods took a 'to' parameter, since, after all, that always needs to be set before sending :)

Another option to improve make_iq_result and make_iq_error would be if you could pass an iq Element, and the make_iq method turns that into the response body, with the to=iq.get('from').

**Comment by legastero** [comment]
Added these and a few extra, useful options to the develop branch.

make_iq_result does not swap the to and from fields though.

**Comment by thom-nic** [comment]
Hey thanks!  I actually forgot that I had even submitted this :)
