### ISSUE TITLE
Sleek should not install signal handlers

### ISSUE THREAD

**Issue by thom-nic** [fritzy/SleekXMPP#75]
xmlstream catches SIGHUP and SIGTERM, which may override some other higher-up logic from doing so.  Basically by doing a _handle_kill in xmlstream you are compensating for lazy users who should be doing this themselves.  

If I have other resource open besides sleek (e.g. a database connection pool, files, etc,) I should have my own signal handler.  But sleek may override _my_ signal handler with its own, then by doing so it causes these other resources to be not cleaned up.

At the very least there should be an option to tell sleek _not_ to add its own signal handlers.

If you are concerned about too many users complaining about "sleek prevents my process from quitting" then the proper solution is to make the sleek child threads daemon threads.  When shutdown is called you can join() with a timeout to give them a chance to quit; if not, it shuts down anyways.

**Comment by macdiesel** [comment]
+1 on this.

**Comment by legastero** [comment]
Daemon threads are indeed the answer. Develop branch now uses those instead of listening for signals.

**Comment by aaronbee** [comment]
I have just tried out the develop branch and I needed to make the scheduler thread a daemon as well to get this to work:
https://gist.github.com/913892

**Comment by legastero** [comment]
Thanks aaronbee, I missed that one. Fixed now in develop branch.
