### ISSUE TITLE
Update plugins so .fulljid and .jid are .boundjid.full and .boundjid.bare

### ISSUE THREAD

**Issue by skinkie** [fritzy/SleekXMPP#76]
diff --git a/sleekxmpp/plugins/gmail_notify.py b/sleekxmpp/plugins/gmail_notify.py
index 7e888b9..9a94a41 100644
--- a/sleekxmpp/plugins/gmail_notify.py
+++ b/sleekxmpp/plugins/gmail_notify.py
@@ -143,7 +143,7 @@ class gmail_notify(base.base_plugin):
             log.info('Gmail: Searching for emails matching: "%s"' % query)
         iq = self.xmpp.Iq()
         iq['type'] = 'get'
-        iq['to'] = self.xmpp.jid
-        iq['to'] = self.xmpp.boundjid.bare
       iq['gmail']['q'] = query
       iq['gmail']['newer-than-time'] = newer
       return iq.send()
  diff --git a/sleekxmpp/plugins/xep_0030.py b/sleekxmpp/plugins/xep_0030.py
  index a3fac34..a6f062f 100644
  --- a/sleekxmpp/plugins/xep_0030.py
  +++ b/sleekxmpp/plugins/xep_0030.py
  @@ -325,5 +325,5 @@ class xep_0030(base.base_plugin):
       self.add_node(node)
       self.add_node(subnode)
       if jid is None:
-            jid = self.xmpp.fulljid
-            jid = self.xmpp.boundjid.full
       self.nodes[node].addItem(jid=jid, name=name, node=subnode)
  diff --git a/sleekxmpp/plugins/xep_0045.py b/sleekxmpp/plugins/xep_0045.py
  index db41cdb..e7f8c7e 100644
  --- a/sleekxmpp/plugins/xep_0045.py
  +++ b/sleekxmpp/plugins/xep_0045.py
  @@ -271,7 +271,7 @@ class xep_0045(base.base_plugin):
      def invite(self, room, jid, reason=''):
              """ Invite a jid to a room."""
              msg = self.xmpp.makeMessage(room)
-               msg['from'] = self.xmpp.jid
-               msg['from'] = self.xmpp.boundjid.bare
              x = ET.Element('{http://jabber.org/protocol/muc#user}x')
              invite = ET.Element('{http://jabber.org/protocol/muc#user}invite', {'to': jid})
              if reason:
  @@ -294,7 +294,7 @@ class xep_0045(base.base_plugin):
      def getRoomConfig(self, room):
              iq = self.xmpp.makeIqGet('http://jabber.org/protocol/muc#owner')
              iq['to'] = room
-               iq['from'] = self.xmpp.jid
-               iq['from'] = self.xmpp.boundjid.bare
              result = iq.send()
              if result is None or result['type'] != 'result':
                      raise ValueError
  @@ -316,7 +316,7 @@ class xep_0045(base.base_plugin):
              query.append(x)
              iq = self.xmpp.makeIqSet(query)
              iq['to'] = room
-               iq['from'] = self.xmpp.jid
- ```
            iq['from'] = self.xmpp.boundjid.bare
          iq.send()
  
  def getJoinedRooms(self):
  ```
  
  diff --git a/sleekxmpp/plugins/xep_0050.py b/sleekxmpp/plugins/xep_0050.py
  index 5efb911..439bebb 100644
  --- a/sleekxmpp/plugins/xep_0050.py
  +++ b/sleekxmpp/plugins/xep_0050.py
  @@ -110,7 +110,7 @@ class xep_0050(base.base_plugin):
              if not id:
                      id = self.xmpp.getNewId()
              iq = self.xmpp.makeIqResult(id)
-               iq.attrib['from'] = self.xmpp.fulljid
-               iq.attrib['from'] = self.xmpp.boundjid.full
              iq.attrib['to'] = to
              command = ET.Element('{http://jabber.org/protocol/commands}command')
              command.attrib['node'] = node
  diff --git a/sleekxmpp/plugins/xep_0060.py b/sleekxmpp/plugins/xep_0060.py
  index a7c6d02..93124fc 100644
  --- a/sleekxmpp/plugins/xep_0060.py
  +++ b/sleekxmpp/plugins/xep_0060.py
  @@ -51,7 +51,7 @@ class xep_0060(base.base_plugin):
              pubsub.append(configure)
              iq = self.xmpp.makeIqSet(pubsub)
              iq.attrib['to'] = jid
-               iq.attrib['from'] = self.xmpp.fulljid
-               iq.attrib['from'] = self.xmpp.boundjid.full
              id = iq['id']
              result = iq.send()
              if result is False or result is None or result['type'] == 'error': return False
  @@ -63,15 +63,15 @@ class xep_0060(base.base_plugin):
              subscribe.attrib['node'] = node
              if subscribee is None:
                      if bare:
-                               subscribe.attrib['jid'] = self.xmpp.jid
-                               subscribe.attrib['jid'] = self.xmpp.boundjid.bare
                      else:
-                               subscribe.attrib['jid'] = self.xmpp.fulljid
-                               subscribe.attrib['jid'] = self.xmpp.boundjid.full
              else:
                      subscribe.attrib['jid'] = subscribee
              pubsub.append(subscribe)
              iq = self.xmpp.makeIqSet(pubsub)
              iq.attrib['to'] = jid
-               iq.attrib['from'] = self.xmpp.fulljid
-               iq.attrib['from'] = self.xmpp.boundjid.full
              id = iq['id']
              result = iq.send()
              if result is False or result is None or result['type'] == 'error': return False
  @@ -83,15 +83,15 @@ class xep_0060(base.base_plugin):
              unsubscribe.attrib['node'] = node
              if subscribee is None:
                      if bare:
-                               unsubscribe.attrib['jid'] = self.xmpp.jid
-                               unsubscribe.attrib['jid'] = self.xmpp.boundjid.bare
                      else:
-                               unsubscribe.attrib['jid'] = self.xmpp.fulljid
-                               unsubscribe.attrib['jid'] = self.xmpp.boundjid.full
              else:
                      unsubscribe.attrib['jid'] = subscribee
              pubsub.append(unsubscribe)
              iq = self.xmpp.makeIqSet(pubsub)
              iq.attrib['to'] = jid
-               iq.attrib['from'] = self.xmpp.fulljid
-               iq.attrib['from'] = self.xmpp.boundjid.full
              id = iq['id']
              result = iq.send()
              if result is False or result is None or result['type'] == 'error': return False
  @@ -109,7 +109,7 @@ class xep_0060(base.base_plugin):
              iq = self.xmpp.makeIqGet()
              iq.append(pubsub)
              iq.attrib['to'] = jid
-               iq.attrib['from'] = self.xmpp.fulljid
-               iq.attrib['from'] = self.xmpp.boundjid.full
              id = iq['id']
              #self.xmpp.add_handler("<iq id='%s'/>" % id, self.handlerCreateNodeResponse)
              result = iq.send()
  @@ -133,7 +133,7 @@ class xep_0060(base.base_plugin):
              iq = self.xmpp.makeIqGet()
              iq.append(pubsub)
              iq.attrib['to'] = jid
-               iq.attrib['from'] = self.xmpp.fulljid
-               iq.attrib['from'] = self.xmpp.boundjid.full
              id = iq['id']
              result = iq.send()
              if result is None or result == False or result['type'] == 'error':
  @@ -156,7 +156,7 @@ class xep_0060(base.base_plugin):
              iq = self.xmpp.makeIqGet()
              iq.append(pubsub)
              iq.attrib['to'] = jid
-               iq.attrib['from'] = self.xmpp.fulljid
-               iq.attrib['from'] = self.xmpp.boundjid.full
              id = iq['id']
              result = iq.send()
              if result is None or result == False or result['type'] == 'error':
  @@ -179,7 +179,7 @@ class xep_0060(base.base_plugin):
              pubsub.append(delete)
              iq.append(pubsub)
              iq.attrib['to'] = jid
-               iq.attrib['from'] = self.xmpp.fulljid
-               iq.attrib['from'] = self.xmpp.boundjid.full
              result = iq.send()
              if result is not None and result is not False and result['type'] != 'error':
                      return True
  @@ -196,7 +196,7 @@ class xep_0060(base.base_plugin):
              pubsub.append(configure)
              iq = self.xmpp.makeIqSet(pubsub)
              iq.attrib['to'] = jid
-               iq.attrib['from'] = self.xmpp.fulljid
-               iq.attrib['from'] = self.xmpp.boundjid.full
              id = iq['id']
              result = iq.send()
              if result is None or result['type'] == 'error':
  @@ -217,7 +217,7 @@ class xep_0060(base.base_plugin):
              pubsub.append(publish)
              iq = self.xmpp.makeIqSet(pubsub)
              iq.attrib['to'] = jid
-               iq.attrib['from'] = self.xmpp.fulljid
-               iq.attrib['from'] = self.xmpp.boundjid.full
              id = iq['id']
              result = iq.send()
              if result is None or result is False or result['type'] == 'error': return False
  @@ -236,7 +236,7 @@ class xep_0060(base.base_plugin):
              pubsub.append(retract)
              iq = self.xmpp.makeIqSet(pubsub)
              iq.attrib['to'] = jid
-               iq.attrib['from'] = self.xmpp.fulljid
-               iq.attrib['from'] = self.xmpp.boundjid.full
              id = iq['id']
              result = iq.send()
              if result is None or result is False or result['type'] == 'error': return False
  @@ -287,7 +287,7 @@ class xep_0060(base.base_plugin):
              pubsub.append(affs)
              iq = self.xmpp.makeIqSet(pubsub)
              iq.attrib['to'] = ps_jid
-               iq.attrib['from'] = self.xmpp.fulljid
- ```
            iq.attrib['from'] = self.xmpp.boundjid.full
          id = iq['id']
          result = iq.send()
          if result is None or result is False or result['type'] == 'error':
  ```
  
  diff --git a/sleekxmpp/plugins/xep_0085.py b/sleekxmpp/plugins/xep_0085.py
  index 3627e71..656698c 100644
  --- a/sleekxmpp/plugins/xep_0085.py
  +++ b/sleekxmpp/plugins/xep_0085.py
  @@ -100,5 +100,5 @@ class xep_0085(base.base_plugin):
  
   def _handleChatState(self, msg):
       state = msg['chat_state'].name
-        log.debug("Chat State: %s, %s" % (state, msg['from'].jid))
-        log.debug("Chat State: %s, %s" % (state, msg['from'].boundjid.bare))
       self.xmpp.event('chatstate_%s' % state, msg)
  diff --git a/sleekxmpp/plugins/xep_0092.py b/sleekxmpp/plugins/xep_0092.py
  index ca02c4a..c9b418f 100644
  --- a/sleekxmpp/plugins/xep_0092.py
  +++ b/sleekxmpp/plugins/xep_0092.py
  @@ -42,7 +42,7 @@ class xep_0092(base.base_plugin):
              query = ET.Element('{jabber:iq:version}query')
              iq.append(query)
              iq.attrib['to'] = jid
-               iq.attrib['from'] = self.xmpp.fulljid
-               iq.attrib['from'] = self.xmpp.boundjid.full
              id = iq.get('id')
              result = iq.send()
              if result and result is not None and result.get('type', 'error') != 'error':

**Comment by louiz** [comment]
Thank you! :)

Forking the project and doing a Pull request would have make it easier to apply your patch, though :p
Github formatted this in a weird manner. Could you try to attach a patch file (or a gist, or whatever)? (or even better, a pull request)

**Comment by skinkie** [comment]
Lets say initially we wanted to setup cgit ourselves for some bizarre reasons this failed, and I just wanted to share my code. Never the less, I am unable to see a button pull request...

In any case, i'll mail you the patch.

**Comment by louiz** [comment]
Thank you.
I pasted your patch here: https://gist.github.com/724621 so it's easier for everyone to review it.

For the Pull Request, you do not need any permission, that's done by forking the project (http://help.github.com/forking/), modifying the code, pushing the code back to github (on your fork) and then sending a Pull Request.

That's the preferred way, but a patch is OK too, I suppose.

Also, I'm not a commiter of SleekXMPP (I haven't any special permission), I'm just a contributor, like you, trying to make things faster and easier to review by getting a patch. Until Lance of Fritzy can merge it.

**Comment by legastero** [comment]
The issue was closed, but I still found it!

Thanks for the contribution skinkie, I applied most of the patches that you sent. (One was already fixed, and another did not need changing).

But yeah, a pull request like louiz mentioned is preferred since it makes the process easier.

Thanks again!

**Comment by skinkie** [comment]
Legastero we are heavily working on the pubsub plugin, so I guess I'll just fork the project and I hope you want to integrate the stuff back. Are you by any chance or IRC somewhere?

**Comment by legastero** [comment]
I'm not on IRC, but join the MUC at sleek@conference.jabber.org. If you're doing a lot of work with the PubSub plugin, we would like to help you out so we can merge things in without making a mess.
