### ISSUE TITLE
Double 'subscribed' sending

### ISSUE THREAD

**Issue by xificurk** [fritzy/SleekXMPP#8]
I've spotted, that sleek is sending subscribed presence twice in response to authorization request. I think it's due to double calling of handler in:
http://github.com/fritzy/SleekXMPP/blob/master/sleekxmpp/__init__.py#L83
http://github.com/fritzy/SleekXMPP/blob/master/sleekxmpp/basexmpp.py#L64

**Comment by fritzy** [comment]
fixed
