### ISSUE TITLE
'bool' object is unsubscriptable in clientxmpp

### ISSUE THREAD

**Issue by thom-nic** [fritzy/SleekXMPP#89]
There are two lines in clientxmpp where the following is used:
    result = iq.send()

However iq.send() appears to simply call xmlstream.send_raw() which always returns `true` not the response packet.

```
2011-03-07 14:13:16,546  SEND: <iq type="get" id="4"><query xmlns="jabber:iq:roster" /></iq>
2011-03-07 14:13:26,545  Timed out waiting for IqWait_4
2011-03-07 14:13:26,546  Error processing event handler: <bound method xmppClient.start of <__main__.xmppClient object at 0x19befd0>>
Traceback (most recent call last):
  File "/home/tnichols/dev/smallfoot/smallfoot-app/ext/sleekxmpp/xmlstream/xmlstream.py", line 996, in _event_runner
    func(*args)
  File "utils/xmppMessagePusher.py", line 43, in start
    self.getRoster()
  File "/home/tnichols/dev/smallfoot/smallfoot-app/ext/sleekxmpp/clientxmpp.py", line 253, in get_roster
    self._handle_roster(response, request=True)
  File "/home/tnichols/dev/smallfoot/smallfoot-app/ext/sleekxmpp/clientxmpp.py", line 467, in _handle_roster
    if iq['type'] == 'set' or (iq['type'] == 'result' and request):
TypeError: 'bool' object is unsubscriptable
```

Which begs the question... What is the proper way of sending a packet and waiting for the response?  xmlstream.send takes a `mask` but any time it's used, a deprecation warning is printed...

**Comment by legastero** [comment]
Iq.send can return three things:
1. The response stanza
2. None, if block=False is used.
3. False if the request timed out.

From the log you included, the request is timing out. Not handling that case properly is a bug, I'll fix that now.

**Comment by thom-nic** [comment]
Thanks for the explanation.  It looks like this is being used in a couple xep plugins too.  It's an easy grep for "iq.send" to find them.

**Comment by thom-nic** [comment]
Did this get fixed?  I'm still confused as to how/where the blocking takes place.  `xmlstream.send()` blocks, but only if a `mask` parameter is given, and then it's always treated as a `MatchXMLMask`.   

`stanzabase.send()` uses `xmlstream.send_raw()`, which as far as I can tell, never blocks...  Don't you just want a `MatcherId` for these cases?  

p.s. I'm working against the 'develop' branch.

**Comment by legastero** [comment]
You want to look at Iq.send(), which overrides StanzaBase.send() to provide the blocking behaviour for replies, with some other useful options. It uses the MatcherId waiter, as you expected.

**Comment by thom-nic** [comment]
I see that now, thanks.

So back to the original issue in `clientxmpp._handle_roster` - since that function is already registered as a callback for roster IQs, it looks like it already handles things...  Except that the `request` arg is never set to `True.`

https://github.com/tomstrummer/SleekXMPP/blob/develop-merge/sleekxmpp/clientxmpp.py#L468

**Comment by legastero** [comment]
_handle_roster() is called with request=True after getting the Iq response
in the get_roster() method. I see that you have commented out that
particular line though.

**Comment by thom-nic** [comment]
Because _handle_roster is already registered as an IQ handler and if you manually call _handle_roster again I think it gets called twice.  No?

**Comment by legastero** [comment]
Ah, very true since the type value of the Iq isn't specified in the callback registration. The handler will be called twice, the first time will exit immediately, and the second time will do the actual update. 

I think the original purpose for this arrangement was to allow for get_roster to block, but if the request parameter is removed then that would still work. The only other reason I can think of would be to not process roster query results automatically, but I can't think of 
why that would be the case. Right now it does look like the request parameter could be removed safely.

**Comment by mattd** [comment]
What's the status of this bug? I ran into the same issues as tomstrummer, but since I'm only just starting with sleekxmpp, I can't yet see the implications of removing the lines you've pointed out.

**Comment by giampaolo** [comment]
Are there news about this issue? 
As a temporary workaround I trapped get_roster() in a try/except block and then called reconnect().
I'm still not sure this is gonna work as the exception occurs randomly.
Nevertheless the drawback is that the last message sent by user gets lost, which is unacceptable for me.

**Comment by legastero** [comment]
Using get_roster will now return None/False/True like Iq.send, and it may also accept the standard block, timeout, and callback arguments as used by Iq.send. The update_roster method was update to fix a similar timeout bug as well.

If a timeout occurs, then the event 'roster_timeout' will be fired. A successful call to get_roster will also raise the 'roster_received' event. 

To ensure that the get_roster call was successful before executing code that depends on the roster, here is one possible pattern to follow:

```
def __init__(self, ...):
    ...
    self.add_event_handler('session_start', self.session_start)
    self.add_event_handler('roster_timeout', self.roster_timeout)
    self.add_event_handler('roster_received', self.roster_received)

def session_start(self, e):
    self.send_presence()
    self.get_roster()

def roster_timeout(self, e):
    # Optionally increase the timeout period
    self.get_roster(timeout=self.response_timeout * 2)

def roster_received(self, iq):
    # Do stuff, roster has been initialized.
    ...
```

**Comment by macdiesel** [comment]
I may have commented on this before, but these functions returning stanza/true/false/none is the worst.  It's bitten me so many times in the past 2 months I've had nightmares about it.  Is there any way we could move away from this paradigm instead of towards it?  

This can be a pretty easy fix I think too... If the call times out, an exception should be thrown. This way you don't have to do all kinds of checking after you make a call to iq.send() (or whatever else works like this).  Maybe it's just the strictly typed language guy in me, but this method returning 3 different types that may need to be checked every time drives me crazy.

Going a step forward I think that there should actually be 2 methods, one to send blocking and one to send non-blocking.  I do realized however that this would break a lot of existing code, but it's probably the more correct way to implement this functionality.  This mixed mode stuff the way it stands now imho puts too much onus on the person making the call.

**Comment by legastero** [comment]
Using exceptions really would be best. I've stayed away from them so far mainly for backwards compatibility issues, but better, cleaner code is better.

There is now an exceptions branch that is based on the develop branch which introduces IqTimeout and IqError exceptions which can be raised by an iq.send() call. Thus the result of iq.send() will either be None (if the call is non-blocking), or the actual result stanza.

So, for the issue at hand, getting the roster can be done using the exceptions branch as:

```
try:
    self.get_roster() # Or anything that uses an iq.send()
except IqTimeout as e:
    # The original sent stanza can be found with e.iq
    log.warning("Roster was not retrieved in time.")
except IqError as e:
    # The error response stanza can be found with e.iq
    log.warning("Roster result was an error: %s" % e.iq)
```

These exceptions would replace the roster_timeout event, etc, that is currently included in the develop branch.

Until significant testing is done, I'm not sure how well the plugins will work with these exceptions, but my few quick tests look like the plugins themselves will work fine, but the result examination process will need to be cleaned up in any user code.

**Comment by macdiesel** [comment]
Cool Lance. I'll merge this change down into my branch and load it on to a few out of devices to test it out.

**Comment by legastero** [comment]
Exceptions are now officially in with RC1 & RC2
