### ISSUE TITLE
Better (de)registering handlers

### ISSUE THREAD

**Issue by xificurk** [fritzy/SleekXMPP#9]
Since basexmpp class automatically generates the name of registered handler ( http://github.com/fritzy/SleekXMPP/blob/master/sleekxmpp/basexmpp.py#L130 ), but doesn't return it, there is currently no way to remove registered handler with xmlstream.removeHandler method.

**Comment by fritzy** [comment]
this is only if you add handlers in a deprecated fashion.  I'll do an audit to get rid of where I am using it and add a deprecated warning for this.

**Comment by fritzy** [comment]
issue created for deprecating this feature.
