### ISSUE TITLE
XMPP Ping XEP-0199 implementation not completely spec-compliant.

### ISSUE THREAD

**Issue by dannmartens** [fritzy/SleekXMPP#97]
In the spec, the 'pong' IQ Result message does not contain the "urn:xmpp:ping" namepace, but Sleek still adds it in the server-to-client ping response (emphasis: server -> client). 

We noticed this happening with a server (Openfire) which has a "urn:xmpp:ping" namespace handler only designed to deal with client-to-server (emphasis: client -> server) ping requests. If the namespace is omitted the handler is not triggered; if it is triggered, it fails because it was not expecting an IQ result. Normally, the pong itself is gobbled up and its reception simply resets the server-side time-out for client connection checking.

**Comment by legastero** [comment]
This is fixed now in the develop branch.

**Comment by legastero** [comment]
Released in RC2
